Repository dhis2/capture-app, pull requests merged in 2022-04, with the labels that each got.

#2696 fix: [DHIS2-12364] use correct fixed length aicode
  src/core_modules/capture-core-utils/rulesEngine/d2Functions/gs1DataMatrixFuntions.js
Labels: back-port

#2699 fix: [DHIS2-12928] handle missing program rules outputConverters
  src/core_modules/capture-core-utils/rulesEngine/constants/typeKeys.const.js
  src/core_modules/capture-core-utils/rulesEngine/constants/typeToInterfaceFnName.const.js
  src/core_modules/capture-core-utils/rulesEngine/processors/rulesEffectsProcessor/rulesEffectsProcessor.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/ProgramRules/getRulesActionsForTEI.js
Labels: back-port

#2705 fix: [DHIS2-13008] fix relationship missing data (#2698)
  src/core_modules/capture-core/relationships/relationshipRequests.js
Labels: back-port, awaiting RCB approval

#2709 fix: [DHIS2-12993] navigate to available tei when switching program (…
  src/core_modules/capture-core/components/Pages/Enrollment/useEnrollmentInfo.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/SingleLockedSelect.component.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetProgramId.js
Labels: back-port

#2710 fix: [DHIS2-12880] refetch tei after updating (#2661)
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/Actions.container.js
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/actions.types.js
  src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.component.js
  src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.container.js
  src/core_modules/capture-core/components/WidgetEnrollment/enrollment.types.js
  src/core_modules/capture-core/components/WidgetEnrollment/hooks/useTrackedEntityInstances.js
Labels: back-port

#2721 fix: [DHIS2-12939] show user error message when event update fails
  i18n/en.pot
  src/core_modules/capture-core/reducers/descriptions/feedback.reducerDescriptionGetter.js
Labels: preview

#2708 chore: [DHIS2-13016] hide Make referral quick action
  cypress/integration/EnrollmentPage/EnrollmentQuickActions.feature
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentQuickActions/EnrollmentQuickActions.component.js
Labels: preview

#2646 fix: [DHIS2-12675] custom relative range for date
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
  i18n/en.pot
  src/core_modules/capture-core/components/FiltersForTypes/Date/DateFilter.component.js
  src/core_modules/capture-core/components/FiltersForTypes/Date/DateFilterManager.component.js
  src/core_modules/capture-core/components/FiltersForTypes/Date/End.component.js
  src/core_modules/capture-core/components/FiltersForTypes/Date/RangeFilter.component.js
  src/core_modules/capture-core/components/FiltersForTypes/Date/Start.component.js
  src/core_modules/capture-core/components/FiltersForTypes/Date/dateFilterDataGetter.js
  src/core_modules/capture-core/components/FiltersForTypes/Date/options.js
  src/core_modules/capture-core/components/FiltersForTypes/Date/types/date.types.js
  src/core_modules/capture-core/components/ListView/Filters/FilterButton/buttonTextBuilder/converters/dateConverter.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/helpers/eventFilters/apiEventFilterToClientConfigConverter/convertToClientConfig.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/helpers/eventFilters/clientConfigToApiEventFilterQueryCriteriaConverter/convertToEventFilterEventQueryCriteria.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/types/apiTemplate.types.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/constants/dates.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/TEIFilters/apiTEIFilterToClientConfigConverter/convertToClientFilters.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/TEIFilters/clientConfigToApiTEIFilterQueryConverter/convertToTEIFilterQuery.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/types/apiTemplate.types.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/helpers/buildFilterQueryArgs/filterConverters/dateConverter.js
  src/core_modules/capture-core/utils/validators/areRelativeRangeValuesSupported.js
Labels: preview

#2703 feat: [DHIS2-12885] Opt in and out of using the Enrollment dashboard
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
  docs/user/resources/images/enrollment-dash-opt-in.png
  docs/user/resources/images/enrollment-dash-opt-out.png
  docs/user/using-the-capture-app.md
  i18n/en.pot
  src/core_modules/capture-core/components/DataStore/DataStore.actions.js
  src/core_modules/capture-core/components/DataStore/DataStore.epics.js
  src/core_modules/capture-core/components/DataStore/DataStore.types.js
  src/core_modules/capture-core/components/DataStore/index.js
  src/core_modules/capture-core/components/OptInOut/OptIn/OptIn.component.js
  src/core_modules/capture-core/components/OptInOut/OptIn/OptIn.container.js
  src/core_modules/capture-core/components/OptInOut/OptIn/index.js
  src/core_modules/capture-core/components/OptInOut/OptIn/optIn.types.js
  src/core_modules/capture-core/components/OptInOut/OptOut/OptOut.component.js
  src/core_modules/capture-core/components/OptInOut/OptOut/OptOut.container.js
  src/core_modules/capture-core/components/OptInOut/OptOut/index.js
  src/core_modules/capture-core/components/OptInOut/OptOut/optOut.types.js
  src/core_modules/capture-core/components/OptInOut/index.js
  src/core_modules/capture-core/components/Pages/MainPage/WorkingListsType/WorkingListsType.component.js
  src/core_modules/capture-core/flow/app-runtime_v2.x.x.js
  src/core_modules/capture-core/metaData/Access/Access.js
  src/core_modules/capture-core/reducers/descriptions/dataStore.reducerDescription.js
Labels: preview

#2748 chore: update semantic checks
  .github/workflows/verify-app.yml
  .github/workflows/verify-pr-title.yml
  commitlint.config.js
Labels: back-port

#2749 chore: update semantic checks
  .github/workflows/verify-app.yml
  .github/workflows/verify-pr-title.yml
  commitlint.config.js
Labels: back-port
