Repository dhis2/capture-app, pull requests merged in 2022-03, with the labels that each got.

#2553 fix: [DHIS2-11280] add default program value (#2435) backport to v37
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/open.epics.js
Labels: back-port

#2554 fix: [DHIS2-11280] add default program value (#2435) backport to v36
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/open.epics.js
Labels: back-port

#2557 fix: [DHIS2-12557] Unique TEAs
  i18n/en.pot
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.component.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.types.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.component.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.container.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.types.js
  src/core_modules/capture-core/components/DataEntries/index.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/UniqueTEADuplicate/ErrorMessageCreator.component.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/UniqueTEADuplicate/ErrorMessageCreator.container.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/UniqueTEADuplicate/ErrorMessageCreator.selectors.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/UniqueTEADuplicate/ExistingTEIContents.component.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/UniqueTEADuplicate/ExistingTEIContents.container.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/UniqueTEADuplicate/ExistingTEILoader.component.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/UniqueTEADuplicate/UniqueTEADuplicate.component.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/UniqueTEADuplicate/existingTeiContents.types.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/index.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/withErrorMessagePostProcessor.js
  src/core_modules/capture-core/components/FormFields/New/HOC/messages/withDisplayMessages.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.component.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/Enrollment/DataEntryEnrollment.component.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/Enrollment/dataEntryEnrollment.types.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/TrackedEntityInstance/DataEntryTrackedEntityInstance.component.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/TrackedEntityInstance/dataEntryTrackedEntityInstance.types.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/RegisterTei.component.js
  src/core_modules/capture-ui/FormBuilder/FormBuilder.component.js
  src/core_modules/capture-ui/FormBuilder/formbuilder.types.js
  src/core_modules/capture-ui/FormBuilder/index.js
Labels: back-port

#2510 [DHIS2-11610] fix: convert the orgUnit attribute to server values
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.actions.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.component.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.container.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
  src/core_modules/capture-ui/FormBuilder/FormBuilder.component.js
Labels: back-port

#2567 fix: [DHIS2-12557] Unique TEAs
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
  i18n/en.pot
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.component.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.types.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.component.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.container.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.types.js
  src/core_modules/capture-core/components/DataEntries/index.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/UniqueTEADuplicate/ErrorMessageCreator.component.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/UniqueTEADuplicate/ErrorMessageCreator.container.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/UniqueTEADuplicate/ErrorMessageCreator.selectors.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/UniqueTEADuplicate/ExistingTEIContents.component.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/UniqueTEADuplicate/ExistingTEIContents.container.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/UniqueTEADuplicate/ExistingTEILoader.component.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/UniqueTEADuplicate/UniqueTEADuplicate.component.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/UniqueTEADuplicate/existingTeiContents.types.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/index.js
  src/core_modules/capture-core/components/DataEntries/withErrorMessagePostProcessor/withErrorMessagePostProcessor.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.component.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/Enrollment/DataEntryEnrollment.component.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/Enrollment/dataEntryEnrollment.types.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/TrackedEntityInstance/DataEntryTrackedEntityInstance.component.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/TrackedEntityInstance/dataEntryTrackedEntityInstance.types.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/RegisterTei.component.js
  src/core_modules/capture-ui/FormBuilder/FormBuilder.component.js
  src/core_modules/capture-ui/FormBuilder/formbuilder.types.js
  src/core_modules/capture-ui/FormBuilder/index.js
Labels: back-port

#2587 fix: fiter options
  src/core_modules/capture-core/metaDataStoreLoaders/optionSets/loadOptionSets.js
Labels: back-port

#2588 fix: [DHIS2-12575] displayColumnOrder name (#2586)
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/TeiWorkingListsSetup.component.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/templates.epics.js
Labels: back-port

#2601 fix: [DHIS2-12667] report date label (#2599)
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/programStage/ProgramStageFactory.js
Labels: back-port

#2605 chore: [DHIS2-12508] fix multi programs message (#2604) backport to v37
  cypress/integration/LockedSelector.feature
  cypress/integration/LockedSelector/index.js
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/Enrollment/MissingMessage.component.js
Labels: back-port

#2608 fix: [DHIS2-12783] hide refer tab (#2590) backport to v38
  cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentAddEventPage.feature
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/NewEventWorkspace/NewEventWorkspace.component.js
Labels: back-port

#2607 chore: [DHIS2-12508] fix multi programs message (#2604) backport to v38
  cypress/integration/EnrollmentPage/EnrollmentPageNavigation/index.js
  cypress/integration/LockedSelector.feature
  cypress/integration/LockedSelector/index.js
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/Enrollment/MissingMessage.component.js
Labels: back-port

#2606 fix: [DHIS2-12778] tooltip display (#2600) backport to v38
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js
Labels: back-port

#2616 fix: [DHIS2-12667] report date label
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/programStage/ProgramStageFactory.js
Labels: back-port

#2615 fix: use api version 38
  .env
Labels: back-port

#2617 feat: [DHIS2-12524] Allow no result to trigger fallback search (#2565) backport to v37
  cypress/integration/SearchPage.feature
  cypress/integration/sharedSteps.js
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.epics.js
Labels: back-port

#2618 feat: [DHIS2-12524] Allow no result to trigger fallback search (#2565) backport to v36
  cypress/integration/SearchPage.feature
  cypress/integration/sharedSteps.js
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.epics.js
Labels: back-port

#2621 fix: [TECH-1027] DisplayName in the comments widget - v38
  src/core_modules/capture-core/components/WidgetComment/CommentSection/CommentSection.js
  src/core_modules/capture-core/components/WidgetEnrollmentComment/WidgetEnrollmentComment.epics.js
Labels: back-port

#2610 feat: [DHIS2-12514] Add new option in enrollment widget (#2531) backport to v38
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.component.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.container.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.types.js
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/Actions.component.js
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/Actions.container.js
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/AddNew/AddNew.component.js
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/AddNew/addNew.types.js
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/AddNew/index.js
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/actions.types.js
  src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.component.js
  src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.container.js
  src/core_modules/capture-core/components/WidgetEnrollment/enrollment.types.js
  src/core_modules/capture-core/components/WidgetEnrollment/hooks/useProgram.js
  src/core_modules/capture-core/components/WidgetEnrollment/hooks/useTrackedEntityInstances.js
Labels: back-port

#2631 fix: [DHIS2-12837] Edit single event epic fix
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.epics.js
Labels: back-port

#2632 fix: [DHIS2-12837] Edit single event epic fix
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.epics.js
Labels: back-port

#2640 fix: remove fields query arg
  src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.epics.js
  src/core_modules/capture-core/components/PossibleDuplicatesDialog/possibleDuplicatesDialog.epics.js
  src/core_modules/capture-core/components/TeiSearch/epics/teiSearch.epics.js
Labels: back-port

#2635 fix: [DHIS2-12740] Send null for erased values
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.epics.js
Labels: back-port

#2638 fix: [DHIS2-12847] Fix app crash when saving TEI without enrollment
  cypress/integration/NewPage.feature
  cypress/integration/SearchPage.feature
  cypress/integration/sharedSteps.js
  src/core_modules/capture-core/actions/navigateToEnrollmentOverview/navigateToEnrollmentOverview.epics.js
Labels: back-port

#2637 fix: [DHIS2-12727][DHIS2-12726] Fix crash when saving event with relationship
  src/core_modules/capture-core/relationships/convertClientToServer.js
  src/core_modules/capture-core/relationships/convertServerToClient.js
  src/core_modules/capture-core/relationships/relationshipRequests.js
Labels: back-port

#2670 fix: [DHIS2-12873] missing propriety for files/images dataElements
  src/core_modules/capture-core/components/WidgetProfile/hooks/getSubValueForTei.js
Labels: back-port

#2671 fix: [DHIS2-12883] use first from multiple order arguments
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/helpers/eventFilters/apiEventFilterToClientConfigConverter/convertToClientConfig.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/TEIFilters/apiTEIFilterToClientConfigConverter/convertSortToClient.js
Labels: back-port

#2665 fix: [DHIS2-12930] add correct fields-filtering on TEI-search
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.epics.js
  src/core_modules/capture-core/components/TeiSearch/epics/teiSearch.epics.js
Labels: preview

#2666 fix: [DHIS2-12930] add fields filtering for tei search - v38
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.epics.js
  src/core_modules/capture-core/components/TeiSearch/epics/teiSearch.epics.js
Labels: back-port

#2675 fix: [DHIS2-12929] use interface language for localeCompare
  i18n/en.pot
  src/core_modules/capture-core/components/FormFields/OrgUnitTree/OrgUnitTree.component.js
  src/core_modules/capture-core/components/Pages/MainPage/WorkingLists/TemplateSelector.component.js
  src/core_modules/capture-core/utils/localeCompareStrings/index.js
  src/core_modules/capture-core/utils/localeCompareStrings/localeCompareStrings.js
Labels: back-port

#2673 fix: [DHIS2-12929] use interface language for localeCompare
  i18n/en.pot
  src/core_modules/capture-core/components/FormFields/OrgUnitTree/OrgUnitTree.component.js
  src/core_modules/capture-core/components/WidgetIndicator/WidgetIndicatorContent/sortIndicatorsFn.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/TemplateSelector.component.js
  src/core_modules/capture-core/utils/localeCompareStrings/index.js
  src/core_modules/capture-core/utils/localeCompareStrings/localeCompareStrings.js
  src/core_modules/capture-core/utils/routing/buildUrlQueryString.js
Labels: back-port

#2682 fix: [DHIS2-12870] use api fields name for TEIFilters
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/TeiWorkingListsSetup.component.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/useDefaultColumnConfig.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/getTemplates.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/convertToClientTeis.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/getTeiListData.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/initTeiWorkingListsView.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/TEIFilters/apiTEIFilterToClientConfigConverter/convertSortToClient.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/TEIFilters/getCustomColumnsConfiguration.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/types/concept.types.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/helpers/buildFilterQueryArgs/filterConverters/dateConverter.js
Labels: back-port

#2690 fix: [DHIS2-11796] adapt the date shape to the API requirements
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/getEventListData.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/TeiWorkingListsSetup.component.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/helpers/buildFilterQueryArgs/filterConverters/dateConverter.js
Labels: back-port

#2680 fix: [DHIS2-12930] add correct fields-filtering on TEI-search - 2.38.0
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.epics.js
  src/core_modules/capture-core/components/TeiSearch/epics/teiSearch.epics.js
Labels: back-port, awaiting RCB approval

#2689 fix: [DHIS2-12950] Use old Tracker Capture dashboard
  cypress/integration/NewPage.feature
  cypress/integration/NewPage/index.js
  cypress/integration/SearchPage.feature
  cypress/integration/SearchPage/index.js
  src/core_modules/capture-core/actions/navigateToEnrollmentOverview/navigateToEnrollmentOverview.epics.js
  src/core_modules/capture-core/components/DataStore/DataStore.actions.js
  src/core_modules/capture-core/components/DataStore/DataStore.epics.js
  src/core_modules/capture-core/components/DataStore/DataStore.types.js
  src/core_modules/capture-core/reducers/descriptions/dataStore.reducerDescription.js
  src/epics/trackerCapture.epics.js
  src/reducers/descriptions/trackerCapture.reducerDescriptions.js
Labels: back-port

#2684 fix: [DHIS2-12966] issues related to invalid property onwerOrgUnit
  src/core_modules/capture-core/actions/navigateToEnrollmentOverview/navigateToEnrollmentOverview.epics.js
  src/core_modules/capture-core/components/WidgetEnrollment/hooks/useTrackedEntityInstances.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/ReduxProvider/TeiWorkingListsReduxProvider.container.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/convertToClientTeis.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/getTeiListData.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/types/getiTeiListDataConcept.types.js
Labels: back-port

#2697 fix: [DHIS2-12966] issues related to invalid property onwerOrgUnit
  i18n/en.pot
  src/core_modules/capture-core/actions/navigateToEnrollmentOverview/navigateToEnrollmentOverview.epics.js
  src/core_modules/capture-core/components/WidgetEnrollment/hooks/useTrackedEntityInstances.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/ReduxProvider/TeiWorkingListsReduxProvider.container.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/convertToClientTeis.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/getTeiListData.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/types/getiTeiListDataConcept.types.js
Labels: back-port
