Repository dhis2/capture-app, pull requests merged in 2022-07, with the labels that each got.

#2882 fix: [DHIS2-12303] enrollment dropdownbutton open state
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/Actions.component.js
Labels: preview

#2851 fix: [DHIS2-13347] uncheck "yes/only" checkboxes
  src/core_modules/capture-ui/internal/SelectionBoxes/SingleSelectionBoxes/SingleSelectBox/SingleSelectBox.component.js
Labels: preview

#2878 fix: [DHIS2-13200] topbaractions redirection and state
  src/core_modules/capture-core/components/TopBarActions/TopBarActions.component.js
  src/core_modules/capture-core/components/TopBarActions/TopBarActions.container.js
  src/core_modules/capture-core/components/TopBarActions/TopBarActions.types.js
Labels: preview

#2892 fix: [DHIS2-13189] fix user name in widget comment
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/epics/dataEntryNote.epics.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.container.js
  src/core_modules/capture-core/components/WidgetEventSchedule/hooks/index.js
  src/core_modules/capture-core/components/WidgetEventSchedule/hooks/useCommentDetails.js
Labels: preview

#2885 fix: [DHIS2-13291] convert dates for auto generated events
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
Labels: preview

#2886 fix: [DHIS2-13291] convert dates for auto generated events
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
Labels: back-port, preview

#2794 fix: [DHIS2-8613] limit report date of new events to today or earlier
  src/core_modules/capture-core-utils/validators/form/index.js
  src/core_modules/capture-core-utils/validators/form/nonFutureDate.validator.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/DataEntry.component.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/fieldValidators/eventDate.validatorContainersGetter.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/DataEntry.component.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/fieldValidators/eventDate.validatorContainersGetter.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/fieldValidators/eventDate.validatorContainersGetter.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.component.js
Labels: preview

#2862 feat: [DHIS2-13308] edit mode for scheduled events
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm.feature
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm/index.js
  docs/user/using-the-capture-app.md
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.types.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/widgetEventEdit.types.js
  src/core_modules/capture-core/hooks/index.js
  src/core_modules/capture-core/hooks/useEnrollmentEditEventPageMode.js
Labels: preview

#2798 feat: [DHIS2-13285] Preserve view settings when changing org unit
  src/core_modules/capture-core/components/List/OnlineList/OnlineList.component.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ContextBuilder/ContextProviders/WorkingListsListViewUpdaterContextProvider.component.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ContextBuilder/ContextProviders/workingListsListViewUpdaterContextProvider.types.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ContextBuilder/WorkingListsContextBuilder.component.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ListViewLoader/ListViewLoader.component.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ListViewLoader/useIsContextInSync.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ListViewUpdater/ListViewUpdater.component.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/workingListsBase.types.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/hooks/useWorkingListsCommonStateManagement.js
  src/core_modules/capture-core/reducers/descriptions/workingLists/meta/meta.reducerDescription.js
  src/core_modules/capture-core/reducers/descriptions/workingLists/workingLists.reducerDescription.js
Labels: preview

#2894 fix: [DHIS2-13188] fix new page crash
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/useRulesEngine.js
Labels: preview

#2850 fix: [DHIS2-13305] compute and inject the download link
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ReduxProvider/EventWorkingListsReduxProvider.container.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ReduxProvider/downloadRequest.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/eventList.epics.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/getEventListData.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/updateEventWorkingList.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/types/concept.types.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ListViewLoader/ListViewLoader.component.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ListViewLoader/listViewLoader.types.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ListViewUpdater/ListViewUpdater.component.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ListViewUpdater/listViewUpdater.types.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/hooks/useWorkingListsCommonStateManagement.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/index.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/types/workingListCommon.types.js
  src/core_modules/capture-core/reducers/descriptions/workingLists/workingLists.reducerDescription.js
Labels: preview

#2891 fix: [DHIS2-13089] trim strings instead of replacing all whitespaces
  src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchFormElementConverter/SearchFormElementConverter.js
Labels: preview

#2883 fix: [DHIS2-13316] remove currentselection and get orgunit from page store
  src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/EventDetailsSection.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/viewEventDataEntry.actions.js
Labels: preview

#2808 fix: [DHIS2-13190][DHIS2-13196] tei geometry
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/DataEntry.container.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/FormFoundation/DataElement.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/FormFoundation/RenderFoundation.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/FormFoundation/types.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/dataEntry.actions.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/dataEntry.epics.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/dataEntry.types.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/helpers/geometry.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/helpers/index.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/helpers/types.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/hooks/index.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/hooks/useGeometryValues.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/hooks/useLifecycle.js
  src/core_modules/capture-core/components/WidgetProfile/WidgetProfile.component.js
  src/core_modules/capture-core/components/WidgetProfile/hooks/useTrackedEntityInstances.js
  src/core_modules/capture-core/constants/geometry.js
  src/core_modules/capture-core/constants/index.js
  src/core_modules/capture-core/reducers/descriptions/trackedEntityInstance.reducerDescription.js
Labels: preview

#2910 chore: jest config update
  jest.config.js
Labels: back-port

#2897 fix: [DHIS2-13230] reimplement code for evaluating program rule expressions
  src/core_modules/capture-core-utils/rulesEngine/d2Functions/d2Functions.js
  src/core_modules/capture-core-utils/rulesEngine/rulesEngine.types.js
  src/core_modules/capture-core-utils/rulesEngine/services/executionService.js
  src/core_modules/capture-core-utils/rulesEngine/services/executionService.types.js
Labels: preview

#2920 fix: [DHIS2-13230] reimplement code for evaluating program rule expressions
  src/core_modules/capture-core-utils/rulesEngine/d2Functions/d2Functions.js
  src/core_modules/capture-core-utils/rulesEngine/rulesEngine.types.js
  src/core_modules/capture-core-utils/rulesEngine/services/executionService.js
  src/core_modules/capture-core-utils/rulesEngine/services/executionService.types.js
Labels: back-port, preview

#2921 fix: [DHIS2-13230] reimplement code for evaluating program rule expressions
  src/core_modules/capture-core/rules/engine/d2Functions/d2Functions.js
  src/core_modules/capture-core/rules/engine/rulesEngine.types.js
  src/core_modules/capture-core/rules/engine/services/executionService.js
  src/core_modules/capture-core/rules/engine/services/executionService.types.js
Labels: back-port, preview

#2911 fix: [DHIS2-13202] fix occurred at label in stages
  cypress/integration/EnrollmentPage/StagesAndEventsWidget.feature
  cypress/integration/EnrollmentPage/StagesAndEventsWidget/index.js
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.component.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/hooks/useEventList.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/types/common.types.js
Labels: preview

#2795 feat: [DHIS2-13279] navigate to register new user
  i18n/en.pot
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/useFormValues.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/useLifecycle.js
  src/core_modules/capture-core/components/Pages/Search/SearchPage.actions.js
  src/core_modules/capture-core/components/Pages/Search/SearchPage.component.js
  src/core_modules/capture-core/components/Pages/Search/SearchPage.container.js
  src/core_modules/capture-core/components/Pages/Search/SearchPage.epics.js
  src/core_modules/capture-core/components/Pages/Search/SearchPage.types.js
  src/epics/trackerCapture.epics.js
Labels: preview

#2916 fix: [DHIS2-12670] delete a "just created" working list
  cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser.feature
  cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser/index.js
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
  src/core_modules/capture-core/reducers/descriptions/workingLists/meta/meta.reducerDescription.js
Labels: preview

#2918 fix: [DHIS2-12670] delete a "just created" working list
  cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser.feature
  cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser/index.js
  src/core_modules/capture-core/reducers/descriptions/workingLists/meta/meta.reducerDescription.js
Labels: back-port, preview

#2845 feat: [DHIS2-13253] enrollmentEventEdit simplify URL parameters
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm.feature
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm/index.js
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageNavigation.feature
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageNavigation/index.js
  cypress/integration/LockedSelector.feature
  cypress/integration/LockedSelector/index.js
  cypress/integration/TopBarActions.feature
  cypress/integration/TopBarActions/index.js
  cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent.feature
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.container.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/TopBar.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/hooks/index.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/hooks/useEvent.js
  src/core_modules/capture-core/components/Pages/New/newPage.epics.js
  src/core_modules/capture-core/components/Pages/Search/SearchPage.epics.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/types.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetEnrollmentId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetEventId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetProgramId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetStageId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetTeiId.js
  src/core_modules/capture-core/components/TopBarActions/TopBarActions.actions.js
  src/core_modules/capture-core/components/TopBarActions/TopBarActions.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/editEventDataEntry.actions.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/epics/cancelEditSingleEvent.epics.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/epics/editEventDataEntry.epics.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/epics/saveEditSingleEvent.epics.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.actions.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.epics.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/widgetEventEdit.types.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/stage.types.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/stages.types.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/stagesAndEvents.types.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/types/common.types.js
  src/core_modules/capture-core/reducers/descriptions/app.reducerDescriptionGetter.js
  src/core_modules/capture-core/reducers/descriptions/feedback.reducerDescriptionGetter.js
  src/epics/trackerCapture.epics.js
Labels: preview

#2923 fix: [DHIS2-12772] change saving text for re-enrollment
  cypress/integration/EnrollmentPage/EnrollmentPageNavigation/index.js
  i18n/en.pot
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.component.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/stage.types.js
Labels: preview

#2896 chore: [DHIS2-13186] add access verification for schedule event widget
  src/core_modules/capture-core/components/WidgetEventSchedule/AccessVerification/NoAccess.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/AccessVerification/index.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.container.js
Labels: preview

#2879 fix: [DHIS2-12304] show enrolllment errors in bottom snackbar
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.component.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.container.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.types.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/enrollment.actions.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/index.js
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/Actions.container.js
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/actions.types.js
  src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.component.js
  src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.container.js
  src/core_modules/capture-core/components/WidgetEnrollment/enrollment.types.js
  src/core_modules/capture-core/reducers/descriptions/feedback.reducerDescriptionGetter.js
Labels: preview

#2881 fix: [DHIS2-12304] show enrolllment errors in snackbar
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.component.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.container.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPage.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPage.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.types.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/enrollment.actions.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/index.js
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/Actions.container.js
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/actions.types.js
  src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.component.js
  src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.container.js
  src/core_modules/capture-core/components/WidgetEnrollment/enrollment.types.js
  src/core_modules/capture-core/reducers/descriptions/feedback.reducerDescriptionGetter.js
Labels: back-port, preview

#2890 chore: [TECH-1233] Refactor OrgUnitField and OrgUnitTree
  src/components/AppStart/appStart.epics.js
  src/components/AppStart/index.js
  src/core_modules/capture-core/components/D2Form/field/Components/OrgUnitField/orgUnitFieldForForms.epics.js
  src/core_modules/capture-core/components/FormFields/New/Fields/OrgUnitField/OrgUnitField.component.js
  src/core_modules/capture-core/components/LockedSelector/QuickSelector/OrgUnitField.container.js
  src/core_modules/capture-core/components/LockedSelector/QuickSelector/OrgUnitSelector.component.js
  src/core_modules/capture-core/components/LockedSelector/QuickSelector/actions/orgUnitList.actions.js
  src/core_modules/capture-core/components/LockedSelector/QuickSelector/epics/orgUnitList.epics.js
  src/core_modules/capture-core/components/LockedSelector/QuickSelector/index.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/OrgUnitField.container.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/OrgUnitSelector.component.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/actions/orgUnitList.actions.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/epics/orgUnitList.epics.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/index.js
  src/core_modules/capture-core/components/TeiSearch/SearchOrgUnitSelector/searchOrgUnitSelector.epics.js
  src/core_modules/capture-core/init/getOrgUnitRootsActions.js
  src/core_modules/capture-core/init/index.js
  src/core_modules/capture-core/init/init.actionBatches.js
  src/core_modules/capture-core/init/init.actions.js
  src/core_modules/capture-core/init/init.epics.js
  src/core_modules/capture-core/reducers/descriptions/feedback.reducerDescriptionGetter.js
  src/core_modules/capture-core/reducers/descriptions/form.reducerDescription.js
  src/core_modules/capture-core/reducers/descriptions/organisationUnits.reducerDescription.js
  src/epics/trackerCapture.epics.js
  src/reducers/descriptions/trackerCapture.reducerDescriptions.js
Labels: preview

#2863 chore: [TECH-1204] clean up location query method
  src/core_modules/capture-core/actions/navigateToEnrollmentOverview/navigateToEnrollmentOverview.epics.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/cancelNewSingleEvent.epics.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/getConvertedNewSingleEvent.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/saveNewSingleEvent.epics.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/saveNewSingleEventStage.epics.js
  src/core_modules/capture-core/components/LockedSelector/LockedSelector.epics.js
  src/core_modules/capture-core/components/LockedSelector/QuickSelector/QuickSelector.container.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.epics.js
  src/core_modules/capture-core/components/Pages/New/newPage.epics.js
  src/core_modules/capture-core/components/Pages/Search/SearchPage.epics.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetEnrollmentId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetEventId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetOrgUnitId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetProgramId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetStageId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetTeiId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useSetEnrollmentId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useSetOrgUnitId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useSetProgramId.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/epics/dataEntryRules.epics.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.container.js
  src/core_modules/capture-core/utils/routing/buildUrlQueryString.js
  src/core_modules/capture-core/utils/routing/getLocationQuery.js
  src/core_modules/capture-core/utils/routing/index.js
  src/core_modules/capture-core/utils/url.js
Labels: preview
