Repository dhis2/capture-app, pull requests merged in 2022-09, with the labels that each got.

#2947 fix: [DHIS2-13545] format updatedAt with the serverTimeZoneId
  i18n/en.pot
  package.json
  src/components/AppLoader/init.js
  src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.component.js
  src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.container.js
  src/core_modules/capture-core/components/WidgetEnrollment/enrollment.types.js
  src/core_modules/capture-core/components/WidgetEnrollment/hooks/useSystemSettings.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageOverview/StageOverview.component.js
  src/core_modules/capture-core/metaDataStoreLoaders/systemSettings/cacheSystemSetttings.js
  src/core_modules/capture-core/utils/cachedDataHooks/useSystemSettingsFromIndexedDB.js
  yarn.lock
Labels: preview

#2778 feat: [DHIS2-12140] working list based on displayfrontpagelist
  cypress/integration/AllAccessibleRecordsPage/index.js
  cypress/integration/EnrollmentPage/EnrollmentPageNavigation/index.js
  cypress/integration/MainPage.feature
  cypress/integration/MainPage/index.js
  cypress/integration/NewPage/index.js
  cypress/integration/ScopeSelector/index.js
  cypress/integration/SearchPage/index.js
  cypress/integration/sharedSteps.js
  docs/user/resources/images/tei_list.png
  docs/user/using-the-capture-app.md
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/MainPage/MainPage.component.js
  src/core_modules/capture-core/components/Pages/MainPage/MainPage.container.js
  src/core_modules/capture-core/components/Pages/MainPage/TopBar.container.js
  src/core_modules/capture-core/components/Pages/MainPage/WorkingListsType/WorkingListsType.component.js
  src/core_modules/capture-core/components/Pages/MainPage/WorkingListsType/workingListsType.types.js
  src/core_modules/capture-core/components/Pages/MainPage/mainPage.types.js
  src/core_modules/capture-core/components/Pages/Search/SearchPage.component.js
  src/core_modules/capture-core/components/Pages/Search/SearchPage.container.js
  src/core_modules/capture-core/components/Pages/Search/SearchPage.types.js
  src/core_modules/capture-core/components/Pages/Search/TemplateSelector/TemplateSelector.component.js
  src/core_modules/capture-core/components/Pages/Search/TemplateSelector/TemplateSelector.container.js
  src/core_modules/capture-core/components/Pages/Search/TemplateSelector/TemplateSelectorChip.component.js
  src/core_modules/capture-core/components/Pages/Search/TemplateSelector/index.js
  src/core_modules/capture-core/components/Pages/Search/TemplateSelector/useTemplates.js
  src/core_modules/capture-core/components/Pages/Search/TemplateSelector/workingListsBase.types.js
  src/core_modules/capture-core/components/Pages/Search/index.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetProgramId.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/ReduxProvider/TeiWorkingListsReduxProvider.container.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/ReduxProvider/teiWorkingListsReduxProvider.types.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/templates.epics.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/teiWorkingLists.types.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/TemplatesManager/TemplatesManager.component.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/actions/workingListsCommon.actions.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/hooks/useWorkingListsCommonStateManagement.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/index.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/types/workingListCommon.types.js
  src/core_modules/capture-core/hooks/index.js
  src/core_modules/capture-core/hooks/useSearchOptions.js
  src/core_modules/capture-core/metaData/Program/Program.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/program/ProgramFactory.js
  src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/storePrograms.js
  src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/types/apiPrograms.types.js
  src/core_modules/capture-core/storageControllers/cache.types.js
  src/core_modules/capture-core/utils/url.js
Labels: preview

#2997 chore: [TECH-1344] run cypress tests agains multiple backend versions
  .env
  .env.cypress
  .github/actions/applicable-released-versions/action.yml
  .github/actions/applicable-released-versions/dist/index.js
  .github/actions/applicable-released-versions/dist/licenses.txt
  .github/actions/applicable-released-versions/index.js
  .github/actions/instance-version/action.yml
  .github/actions/instance-version/dist/index.js
  .github/actions/instance-version/dist/licenses.txt
  .github/actions/instance-version/index.js
  .github/workflows/e2e-tests-exceptions.yml
  .github/workflows/e2e-tests-result.yml
  .github/workflows/e2e-tests-skip.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/preview.yml
  .github/workflows/verify-app.yml
  cypress/integration/AllAccessibleRecordsPage/index.js
  cypress/integration/EnrollmentAddEventPage/EnrollmentAddEventPageForm/index.js
  cypress/integration/EnrollmentAddEventPage/EnrollmentAddEventPageNavigation/index.js
  cypress/integration/EnrollmentAddEventPage/ProgramStageSelector/index.js
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm/index.js
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageNavigation/index.js
  cypress/integration/EnrollmentPage/EnrollmentPageNavigation/index.js
  cypress/integration/EnrollmentPage/EnrollmentQuickActions/index.js
  cypress/integration/EnrollmentPage/StagesAndEventsWidget/index.js
  cypress/integration/MainPage/index.js
  cypress/integration/NewEventThroughAddRelationship/index.js
  cypress/integration/NewPage.feature
  cypress/integration/NewPage/index.js
  cypress/integration/Platform.feature
  cypress/integration/ScopeSelector/index.js
  cypress/integration/SearchForDuplicatesThroughAddRelationship/index.js
  cypress/integration/SearchPage.feature
  cypress/integration/SearchPage/index.js
  cypress/integration/SearchThroughAddRelationship/index.js
  cypress/integration/StageEventListPage/StageEventListNavigation/index.js
  cypress/integration/TopBarActions/index.js
  cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentAddEventPage/index.js
  cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard/index.js
  cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent/index.js
  cypress/integration/WidgetsForEnrollmentPages/WidgetsForEventSchedule/index.js
  cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsDev/index.js
  cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser/index.js
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsDev/index.js
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
  cypress/integration/common/index.js
  cypress/plugins/getCypressEnvVariables.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/support/tagUtils/filterInstanceVersion.js
  cypress/support/tagUtils/index.js
  cypress/support/tagUtils/shouldLogin.js
  package.json
  scripts/startAppForCypress.js
  yarn.lock
Labels: testing

#2866 refactor: [TECH-836] remove d2 config and baseUrl
  src/core_modules/capture-core/actions/navigateToEnrollmentOverview/navigateToEnrollmentOverview.epics.js
  src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.epics.js
  src/core_modules/capture-core/components/Pages/ViewEvent/epics/editEvent.epics.js
  src/core_modules/capture-core/components/Pages/ViewEvent/epics/viewEvent.epics.js
  src/core_modules/capture-core/components/PossibleDuplicatesDialog/possibleDuplicatesDialog.epics.js
  src/core_modules/capture-core/components/TeiSearch/epics/teiSearch.epics.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ViewMenuSetup/DownloadDialog/DownloadDialog.component.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ViewMenuSetup/DownloadDialog/downloadDialog.types.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ViewMenuSetup/EventWorkingListsViewMenuSetup.component.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/eventList.epics.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/getEventListData.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/initEventWorkingList.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/updateEventWorkingList.js
  src/core_modules/capture-core/events/eventRequests.js
  src/core_modules/capture-core/events/getSubValues.js
  src/core_modules/capture-core/trackedEntityInstances/getSubValues.js
  src/core_modules/capture-core/trackedEntityInstances/trackedEntityInstanceRequests.js
Labels: preview

#2908 refactor: [TECH-1270] initialisation of main page from TopBar buttons
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/newEventDataEntry.epics.js
  src/core_modules/capture-core/components/Pages/MainPage/MainPage.actions.js
  src/core_modules/capture-core/components/Pages/MainPage/TopBar.container.js
  src/core_modules/capture-core/components/Pages/New/NewPage.actions.js
  src/core_modules/capture-core/components/Pages/New/TopBar.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/TopBar.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventPage.actions.js
  src/core_modules/capture-core/components/Pages/epics/calculateSelectionsCompleteness.epic.js
  src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.actions.js
  src/core_modules/capture-core/components/ScopeSelector/index.js
  src/core_modules/capture-core/components/TopBarActions/TopBarActions.container.js
  src/core_modules/capture-core/reducers/descriptions/currentSelections.reducerDescriptionGetter.js
Labels: testing

#2960 chore: [TECH-1317] migrate tooltip to dhis2/ui
  cypress/integration/EnrollmentPage/EnrollmentQuickActions/index.js
  cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser/index.js
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
  i18n/en.pot
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/withMainButton.js
  src/core_modules/capture-core/components/DataTable/SortLabelWrapper.component.js
  src/core_modules/capture-core/components/FormFields/Options/SelectVirtualizedV2/OptionsSelectVirtualizedOption.component.js
  src/core_modules/capture-core/components/ListView/ColumnSelector/ColumnSelector.component.js
  src/core_modules/capture-core/components/ListView/Filters/FilterButton/ActiveFilterButton.component.js
  src/core_modules/capture-core/components/Notes/Notes.component.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentQuickActions/EnrollmentQuickActions.component.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentQuickActions/QuickActionButton/QuickActionButton.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/ProgramStageSelector/ProgramStageSelector.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/EventDetailsSection.component.js
  src/core_modules/capture-core/components/Relationships/Relationships.component.js
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/AddNew/AddNew.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/withMainButton.js
Labels: testing

#2875 chore: [TECH-840] migrate getD2
  src/components/App/AppPagesLoader.component.js
  src/components/AppLoader/AppLoader.component.js
  src/components/AppLoader/init.js
  src/core_modules/capture-core-utils/rulesEngine/RulesEngine.js
  src/core_modules/capture-core-utils/rulesEngine/rulesEngine.types.js
  src/core_modules/capture-core/HOC/index.js
  src/core_modules/capture-core/HOC/withD2InContext.js
  src/core_modules/capture-core/components/D2Form/field/Components/OrgUnitField/orgUnitFieldForForms.epics.js
  src/core_modules/capture-core/components/FormFields/New/Fields/OrgUnitField/withInternalFilterHandler/withImplicitRootsInternalFilterHandler.js
  src/core_modules/capture-core/components/FormFields/New/Fields/OrgUnitField/withInternalFilterHandler/withInternalFilterHandler.js
  src/core_modules/capture-core/components/FormFields/OrgUnitTree/OrgUnitTree.component.js
  src/core_modules/capture-core/components/TeiSearch/SearchOrgUnitSelector/searchOrgUnitSelector.epics.js
  src/core_modules/capture-core/d2/d2Instance.js
  src/core_modules/capture-core/d2/index.js
  src/core_modules/capture-core/events/getSubValues.js
  src/core_modules/capture-core/rules/__tests__/__snapshots__/getApplicableRuleEffectsForTrackerProgram.test.js.snap
  src/core_modules/capture-core/rules/__tests__/__snapshots__/getApplicableRulesEffectsForEventProgram.test.js.snap
  src/core_modules/capture-core/rules/__tests__/getApplicableRuleEffectsForTrackerProgram.test.js
  src/core_modules/capture-core/rules/__tests__/getApplicableRulesEffectsForEventProgram.test.js
  src/core_modules/capture-core/rules/getApplicableRuleEffects.js
  src/core_modules/capture-core/trackedEntityInstances/trackedEntityInstanceRequests.js
Labels: testing

#3003 chore: [TECH-1411] remove d2 package
  package.json
  yarn.lock
Labels: testing

#2981 fix: [DHIS2-13544] form validation for scheduled event
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm.feature
  cypress/integration/ScopeSelector.feature
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.constants.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/TopBar.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/EventDetailsSection.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/eventDetails.actions.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/ViewEvent.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventPage.container.js
  src/core_modules/capture-core/components/WidgetEventComment/WidgetEventComment.component.js
  src/core_modules/capture-core/components/WidgetEventComment/WidgetEventComment.types.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/editEventDataEntry.actions.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.epics.js
  src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/ViewEventDataEntry.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/viewEventDataEntry.actions.js
  src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/viewEventDataEntry.epics.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/widgetEventEdit.types.js
  src/core_modules/capture-core/constants/dataEntries.js
  src/core_modules/capture-core/constants/index.js
  src/core_modules/capture-core/hooks/useEnrollmentEditEventPageMode.js
Labels: testing

#3001 fix: [DHIS2-13723] send program id from event
  i18n/en.pot
  src/core_modules/capture-core/components/CardList/CardList.types.js
  src/core_modules/capture-core/components/CardList/CardListItem.component.js
  src/core_modules/capture-core/components/Pages/Search/SearchResults/SearchResults.component.js
Labels: testing

#3011 chore: skip CI release for dependabot PRs
  .github/workflows/verify-app.yml
Labels: skip-e2e-tests

#3010 chore: [TECH-862] [TECH-1409] fix cypress tests
  cypress/integration/NewEventThroughAddRelationship.feature
  cypress/integration/NewEventThroughAddRelationship/index.js
  cypress/integration/NewPage.feature
  cypress/integration/NewPage/index.js
  cypress/integration/Platform.feature
  cypress/integration/SearchPage.feature
  cypress/integration/SearchPage/index.js
  cypress/integration/SmokeTests.feature
  cypress/integration/SmokeTests/LoginWithUserEnglish.feature
  cypress/integration/SmokeTests/LoginWithUserEnglish/index.js
  cypress/integration/SmokeTests/index.js
  cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser.feature
  cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser/index.js
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
  src/core_modules/capture-ui/FormBuilder/FormBuilder.component.js
Labels: back-port

#3012 chore: [DHIS2-13799] disable Show teis ordered descendingly by first name
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsDev.feature
Labels: testing

#3008 feat: [DHIS2-13739] navigate to new tracker based on opt-in func
  src/core_modules/capture-core/actions/navigateToEnrollmentOverview/navigateToEnrollmentOverview.epics.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
  src/core_modules/capture-core/components/Pages/ViewEvent/RightColumn/RelationshipsSection/ConnectedEntity/TrackedEntityInstance.js
  src/core_modules/capture-core/relationships/convertServerToClient.js
  src/core_modules/capture-core/utils/routing/index.js
  src/core_modules/capture-core/utils/routing/newDashboard.js
Labels: testing

#2893 fix: [DHIS2-11514] use org unit code
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.actions.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.container.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.epics.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.actions.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.container.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.epics.js
  src/core_modules/capture-core/hooks/useCurrentOrgUnitInfo.js
Labels: back-port, preview

#2898 fix: [DHIS2-11514] use org unit code
  cypress/integration/LockedSelector.feature
  package.json
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.actions.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.container.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.epics.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.actions.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.container.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.epics.js
  src/core_modules/capture-core/hooks/useCurrentOrgUnitInfo.js
  yarn.lock
Labels: back-port, preview

#3013 chore: add local Cypress testing info to README
  README.md
Labels: skip-e2e-tests
