Repository dhis2/capture-app, pull requests merged in 2022-10, with the labels that each got.

#2994 feat: [DSHI2-13309] add schedule date in view/edit event page
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm.feature
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm/index.js
  i18n/en.pot
  src/core_modules/capture-core/components/FormFields/New/HOC/withLabel.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.epics.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/index.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/helpers/getOpenDataEntryActions.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/editEventDataEntry.actions.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.actions.js
  src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/ViewEventDataEntry.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/index.js
  src/core_modules/capture-core/components/WidgetEventEdit/widgetEventEdit.types.js
  src/core_modules/capture-core/components/WidgetEventSchedule/ScheduleDate/ScheduleDate.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.actions.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.container.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.epics.js
  src/core_modules/capture-core/components/WidgetEventSchedule/hooks/useDetermineSuggestedScheduleDate.js
  src/core_modules/capture-core/components/WidgetEventSchedule/index.js
  src/core_modules/capture-core/components/WidgetEventSchedule/widgetEventSchedule.types.js
  src/core_modules/capture-core/utils/converters/date/index.js
  src/core_modules/capture-core/utils/converters/date/stringToMomentDateFormat.js
  src/core_modules/capture-ui/DateAndTimeFields/DateField/Date.component.js
  src/core_modules/capture-ui/internal/TextInput/TextInput.component.js
  src/epics/trackerCapture.epics.js
Labels: testing

#3017 fix: [DHIS2-8210] display order of tracked entity attributes
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/enrollment/EnrollmentFactory.js
Labels: back-port, preview, testing

#2987 fix: [DHIS2-8210] use display order given in TEA registration form
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/FormFoundation/RenderFoundation.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/enrollment/EnrollmentFactory.js
Labels: testing

#3005 chore: [TECH-862] [TECH-1409] fix cypress tests
  cypress/integration/AllAccessibleRecordsPage.feature
  cypress/integration/AllAccessibleRecordsPage/index.js
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageNavigation.feature
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageNavigation/index.js
  cypress/integration/EnrollmentPage/EnrollmentQuickActions.feature
  cypress/integration/EnrollmentPage/StagesAndEventsWidget.feature
  cypress/integration/EnrollmentPage/StagesAndEventsWidget/index.js
  cypress/integration/MainPage.feature
  cypress/integration/MainPage/index.js
  cypress/integration/NewEventThroughAddRelationship.feature
  cypress/integration/NewEventThroughAddRelationship/index.js
  cypress/integration/NewPage.feature
  cypress/integration/NewPage/index.js
  cypress/integration/Platform.feature
  cypress/integration/SearchPage.feature
  cypress/integration/SearchPage/index.js
  cypress/integration/SmokeTests.feature
  cypress/integration/SmokeTests/LoginWithUserEnglish/index.js
  cypress/integration/SmokeTests/index.js
  cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser.feature
  cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser/index.js
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
  cypress/integration/sharedSteps.js
  src/core_modules/capture-ui/FormBuilder/FormBuilder.component.js
Labels: e2e-tests

#2996 feat: [DHIS2-13439] show description due date label when available
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.container.js
  src/core_modules/capture-core/components/WidgetEventSchedule/hooks/useScheduleConfigFromProgramStage.js
  src/core_modules/capture-core/components/WidgetEventSchedule/widgetEventSchedule.types.js
Labels: testing

#2973 fix: [DHIS2-13635] cover the case `ai.length > 2`
  src/core_modules/capture-core-utils/rulesEngine/d2Functions/gs1DataMatrixFuntions.js
Labels: testing

#3020 feat: [DHIS2-13681] optional decimal places argument for d2:round
  src/core_modules/capture-core-utils/rulesEngine/d2Functions/getD2Functions.js
  src/core_modules/capture-core-utils/rulesEngine/d2Functions/getD2Functions.types.js
  src/core_modules/capture-core-utils/rulesEngine/d2Functions/index.js
  src/core_modules/capture-core-utils/rulesEngine/services/expressionService/executeExpression.js
Labels: testing

#3060 feat: [DHIS2-13749][DHIS2-13750] filter and sort by both TEA and data elements
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
  i18n/en.pot
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/TeiWorkingListsSetup.component.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/useDefaultColumnConfig.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/constants/additionalFilters.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getEventListData/getEventListData.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getListDataCommon/getFilterQueryArgs.js
Labels: e2e-tests

#3055 fix: [DHIS2-13906] variable names with spaces in rules engine
  src/core_modules/capture-core-utils/rulesEngine/services/expressionService/injectVariableValues.js
Labels: preview, e2e-tests

#3057 fix: [DHIS2-13906] variable names with spaces in rules engine
  src/core_modules/capture-core/rules/engine/services/expressionService/injectVariableValues.js
Labels: back-port, preview

#3066 chore: [DHIS2-13960] disable failed cypress test
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
Labels: skip-e2e-tests
