Repository dhis2/capture-app, pull requests merged in 2022-11, with the labels that each got.

#3088 feat: [DHIS2-13748] remove filter button
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
  cypress/integration/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
  i18n/en.pot
  src/core_modules/capture-core/components/ListView/Filters/Contents/FilterSelectorContents.component.js
  src/core_modules/capture-core/components/ListView/Filters/Contents/filterSelectorContents.types.js
  src/core_modules/capture-core/components/ListView/Filters/Contents/withButtons.js
  src/core_modules/capture-core/components/ListView/Filters/FilterButton/FilterButtonMain.component.js
  src/core_modules/capture-core/components/ListView/Filters/FilterButton/filterButton.types.js
  src/core_modules/capture-core/components/ListView/Filters/Filters.component.js
  src/core_modules/capture-core/components/ListView/Filters/FiltersRows.component.js
  src/core_modules/capture-core/components/ListView/Main/withFilters.js
  src/core_modules/capture-core/components/ListView/index.js
  src/core_modules/capture-core/components/ListView/types/listView.types.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ReduxProvider/eventWorkingListsReduxProvider.types.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/ReduxProvider/teiWorkingListsReduxProvider.types.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ContextBuilder/ContextProviders/WorkingListsListViewBuilderContextProvider.component.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ContextBuilder/ContextProviders/workingListsListViewBuilderContextProvider.types.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ContextBuilder/WorkingListsContextBuilder.component.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/ContextBuilder/workingListsContextBuilder.types.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/index.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/workingListsBase.types.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/actions/workingListsCommon.actions.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/hooks/useWorkingListsCommonStateManagement.js
  src/core_modules/capture-core/reducers/descriptions/workingLists/meta/meta.reducerDescription.js
  src/core_modules/capture-core/reducers/descriptions/workingLists/workingLists.reducerDescription.js
Labels: testing

#2691 docs: change TEI profile widget
  docs/user/using-the-capture-app.md
Labels: skip-e2e-tests

#3035 fix: [DHIS2-13720] get image and file subvalues in widget stages
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/hooks/helpers.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/hooks/useEventList.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/getEventDataWithSubValue.js
Labels: testing

#3067 fix: [DHIS2-13665] use the downloadRequest url
  i18n/en.pot
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ViewMenuSetup/DownloadDialog/DownloadDialog.component.js
Labels: testing

#3058 feat: [DHIS2-13895] show scheduled date for active/complete events
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm.feature
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm/index.js
  i18n/en.pot
  src/core_modules/capture-core/components/FormFields/New/HOC/withLabel.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/ViewEventDataEntry.component.js
Labels: testing

#3084 fix: [DHIS2-13941] adjust notice box for schedule events
  i18n/en.pot
  src/core_modules/capture-core/components/WidgetEventSchedule/InfoBox/InfoBox.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.component.js
Labels: testing

#3097 chore: [DHIS2-13943] adjust save new button to save tetype
  cypress/integration/NewPage.feature
  cypress/integration/NewPage/index.js
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.component.js
Labels: testing

#3096 fix: [DHIS2-14081] use static style for accessory row in events table
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js
Labels: testing

#3099 fix: [DHIS2-7913] apply hide fields program rule in form view mode
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm.feature
  src/core_modules/capture-core/components/D2Form/field/Components/ViewModeField/ViewModeFieldForCustomForm.component.js
  src/core_modules/capture-core/components/D2Form/field/Components/ViewModeField/ViewModeFieldForForm.component.js
Labels: testing

#3100 fix: [DHIS2-7913] apply hide fields program rule in form view mode
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm.feature
  src/core_modules/capture-core/components/D2Form/field/Components/ViewModeField/ViewModeFieldForCustomForm.component.js
  src/core_modules/capture-core/components/D2Form/field/Components/ViewModeField/ViewModeFieldForForm.component.js
Labels: back-port, preview

#3109 fix: [DHIS2-14001] complete enrollment action label
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/Complete/Complete.component.js
Labels: back-port, preview

#3110 fix: [DHIS2-14001] complete enrollment action label
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/Complete/Complete.component.js
Labels: testing

#3054 feat: [DHIS2-13897] respect Hide due date flag
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm.feature
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm/index.js
  i18n/en.pot
  src/core_modules/capture-core/components/FormFields/New/HOC/withLabel.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/NewEventWorkspace/NewEventWorkspace.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/ViewEventDataEntry.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
  src/core_modules/capture-core/components/WidgetEventSchedule/InfoBox/InfoBox.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/InfoBox/infoBox.types.js
  src/core_modules/capture-core/components/WidgetEventSchedule/ScheduleDate/ScheduleDate.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/ScheduleDate/scheduleDate.types.js
  src/core_modules/capture-core/components/WidgetEventSchedule/hooks/useDetermineSuggestedScheduleDate.js
  src/core_modules/capture-core/components/WidgetEventSchedule/widgetEventSchedule.types.js
  src/core_modules/capture-core/metaData/Program/ProgramStage.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/programStage/ProgramStageFactory.js
  src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/storePrograms.js
  src/core_modules/capture-core/storageControllers/cache.types.js
Labels: testing

#3019 feat: [DHIS2-9666] Create new TEI when none of the results match
  cypress/integration/SearchPage/index.js
  i18n/en.pot
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.actions.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.container.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.epics.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/hooks/useFormValuesFromSearchTerms.js
  src/core_modules/capture-core/components/DataEntries/TrackedEntityInstance/actions/open.actionBatches.js
  src/core_modules/capture-core/components/Pages/Search/SearchPage.epics.js
  src/core_modules/capture-core/components/Pages/Search/SearchResults/SearchResults.component.js
  src/core_modules/capture-core/components/Pages/Search/SearchResults/SearchResults.container.js
  src/core_modules/capture-core/components/Pages/Search/SearchResults/SearchResults.types.js
  src/core_modules/capture-core/converters/clientToForm.js
  src/core_modules/capture-core/converters/clientToList.js
Labels: testing

#3022 docs: [DHIS2-13309] edit scheduled date for schedule/overdue event
  docs/user/resources/images/enrollment-edit-event-schedule-date-1.png
  docs/user/resources/images/enrollment-edit-event-schedule-date.png
  docs/user/using-the-capture-app.md
Labels: skip-e2e-tests

#3021 docs: [DHIS2-9666] create new tei in search page
  docs/user/resources/images/search-page-create-new-tei.png
  docs/user/using-the-capture-app.md
Labels: skip-e2e-tests

#3113 chore: update code owners
  CODEOWNERS
Labels: skip-e2e-tests

#3092 docs: [DHIS2-13654] program stage working list docs
  docs/user/resources/images/program_stage_button.png
  docs/user/resources/images/program_stage_working_list.png
  docs/user/using-the-capture-app.md
Labels: skip-e2e-tests

#3065 feat: [DHIS2-13801] ask to create new after completing the event
  cypress/integration/EnrollmentAddEventPage/EnrollmentAddEventPageForm.feature
  cypress/integration/EnrollmentAddEventPage/EnrollmentAddEventPageForm/index.js
  cypress/integration/EnrollmentAddEventPage/EnrollmentAddEventPageNavigation/index.js
  cypress/integration/EnrollmentAddEventPage/sharedSteps.js
  i18n/en.pot
  src/core_modules/capture-core/components/DataEntry/index.js
  src/core_modules/capture-core/components/DataEntry/withAskToCreateNew.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.component.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/Validated.container.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/validated.actions.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.actions.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.epics.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/widgetEventEdit.types.js
  src/core_modules/capture-core/hooks/index.js
  src/core_modules/capture-core/hooks/useAvailableProgramStages.js
  src/core_modules/capture-core/metaData/Program/ProgramStage.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/programStage/ProgramStageFactory.js
  src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/storePrograms.js
  src/core_modules/capture-core/storageControllers/cache.types.js
  src/epics/trackerCapture.epics.js
Labels: testing

#3111 fix: [DHIS2-13968] report date and enrollment date without hours
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
  src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.utils.js
  src/core_modules/capture-core/converters/clientToView.js
  src/core_modules/capture-core/converters/index.js
Labels: testing

#3117 docs: [DHIS2-13801] add doc for ask to create new event after completing
  docs/user/using-the-capture-app.md
Labels: skip-e2e-tests

#3115 fix: [DHIS2-14156] program stage WL event status convertor
  i18n/en.pot
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/hooks/helpers.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getEventListData/convertToClientEvents.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getEventListData/types/getEventListDataConcept.types.js
  src/core_modules/capture-core/events/statusTypes.js
  src/core_modules/capture-core/utils/isEventOverdue.js
Labels: testing
