Repository dhis2/capture-app, pull requests merged in 2023-10, with the labels that each got.

#3424 docs: [DHIS2-9661] first stage appears on registration page
  docs/user/resources/images/first-stage-during-registration.png
  docs/user/using-the-capture-app.md
Labels: skip-e2e-tests

#3422 fix: [DHIS2-15734] assign effect dynamic formId object key
  src/core_modules/capture-core/reducers/descriptions/form.reducerDescription.js
Labels: testing

#3418 fix: [DHIS2-15827] remove effects of 'Prevent adding new events to stage' action from the form
  cypress/integration/EnrollmentPage/HiddenProgramStage.feature
  cypress/integration/EnrollmentPage/HiddenProgramStage/index.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/ErrorText/ErrorText.component.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/ErrorText/ErrorText.types.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/ErrorText/index.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/FinishButtons/FinishButtons.component.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/FinishButtons/finishButtons.types.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/Validated.component.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/Validated.container.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/validated.types.js
Labels: testing

#3432 feat: [DHIS2-15906] Add form features for relationship
  CHANGELOG.md
  cypress/integration/EnrollmentPage/HiddenProgramStage.feature
  cypress/integration/EnrollmentPage/HiddenProgramStage/index.js
  docs/user/resources/images/first-stage-during-registration.png
  docs/user/using-the-capture-app.md
  package.json
  packages/rules-engine/package.json
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.container.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.types.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/useBuildEnrollmentPayload.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/useLifecycle.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.container.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.types.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/hooks/useBuildTeiPayload.js
  src/core_modules/capture-core/components/DataEntries/common/TEIAndEnrollment/DuplicateCheckOnSave/types/duplicateCheckOnSave.types.js
  src/core_modules/capture-core/components/DataEntries/common/TEIAndEnrollment/DuplicateCheckOnSave/useDuplicateCheckerOnSave.types.js
  src/core_modules/capture-core/components/DataEntries/common/TEIAndEnrollment/DuplicateCheckOnSave/withDuplicateCheckOnSave.types.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.actions.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.component.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.container.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/helpers/deriveAutoGenerateEvents.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/helpers/deriveFirstStageDuringRegistrationEvent.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/helpers/getStageWithOpenAfterEnrollment.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/TrackedEntityInstance/dataEntryTrackedEntityInstance.types.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/RegisterTei/DataEntry/RegisterTeiDataEntry.component.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/RegisterTei/DataEntry/TrackedEntityInstance/dataEntryTrackedEntityInstance.types.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/RegisterTei/RegisterTei.component.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/RegisterTei/RegisterTei.container.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/RegisterTei/RegisterTei.types.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/TrackedEntityRelationshipsWrapper/hooks/useDataEntryReduxConverter.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/ErrorText/ErrorText.component.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/ErrorText/ErrorText.types.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/ErrorText/index.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/FinishButtons/FinishButtons.component.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/FinishButtons/finishButtons.types.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/Validated.component.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/Validated.container.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/validated.types.js
  src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/NewTrackedEntityRelationship/NewTrackedEntityRelationship.component.js
  src/core_modules/capture-core/reducers/descriptions/form.reducerDescription.js
Labels: testing

#3430 docs: [DHIS2-12361] Relationships widget
  docs/user/resources/images/enrollment-dash-relationship-widget-add-choose.png
  docs/user/resources/images/enrollment-dash-relationship-widget-add-existing.png
  docs/user/resources/images/enrollment-dash-relationship-widget-add-new.png
  docs/user/resources/images/enrollment-dash-relationship-widget-add.png
  docs/user/resources/images/enrollment-dash-relationship-widget.png
  docs/user/using-the-capture-app.md
Labels: skip-e2e-tests

#3436 refactor: [TECH-1657] standardize format of redux orgunits
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentAddEventPage.feature
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard.feature
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent.feature
  packages/rules-engine/src/rulesEngine.types.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.container.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/NewEventDataEntryWrapper.component.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.component.js
  src/core_modules/capture-core/components/DataEntries/TrackedEntityInstance/TrackedEntityInstanceDataEntry.component.js
  src/core_modules/capture-core/components/LockedSelector/LockedSelector.actions.js
  src/core_modules/capture-core/components/LockedSelector/LockedSelector.epics.js
  src/core_modules/capture-core/components/OrgUnitFetcher/OrgUnitFetcher.actions.js
  src/core_modules/capture-core/components/OrgUnitFetcher/OrgUnitFetcher.component.js
  src/core_modules/capture-core/components/OrgUnitFetcher/OrgUnitFetcher.epics.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/ProgramStageSelector/ProgramStageSelector.container.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.component.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/TrackedEntityInstance/DataEntryTrackedEntityInstance.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/EventDetailsSection.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/epics/viewEvent.epics.js
  src/core_modules/capture-core/components/PossibleDuplicatesDialog/useDuplicates.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/actions/QuickSelector.actions.js
  src/core_modules/capture-core/components/ScopeSelector/SingleLockedSelect/SingleLockedSelect.component.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/OrgUnitFetcher/OrgUnitFetcher.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
  src/core_modules/capture-core/dataQueries/useOrganisationUnit.js
  src/core_modules/capture-core/hooks/index.js
  src/core_modules/capture-core/hooks/useCurrentOrgUnitId.js
  src/core_modules/capture-core/hooks/useCurrentOrgUnitInfo.js
  src/core_modules/capture-core/hooks/useRulesEngineOrgUnit.js
  src/core_modules/capture-core/metadataRetrieval/coreOrgUnit/coreOrgUnit.actions.js
  src/core_modules/capture-core/metadataRetrieval/coreOrgUnit/coreOrgUnit.types.js
  src/core_modules/capture-core/metadataRetrieval/coreOrgUnit/fetchCoreOrgUnit.js
  src/core_modules/capture-core/metadataRetrieval/coreOrgUnit/getCoreOrgUnit.epics.js
  src/core_modules/capture-core/metadataRetrieval/coreOrgUnit/index.js
  src/core_modules/capture-core/metadataRetrieval/coreOrgUnit/useCoreOrgUnit.js
  src/core_modules/capture-core/reducers/descriptions/organisationUnits.reducerDescription.js
  src/epics/trackerCapture.epics.js
Labels: e2e-tests

#3421 fix: [DHIS2-15879] Unable to schedule event with note
  cypress/e2e/EnrollmentAddEventPage/EnrollmentAddEventPageForm.feature
  cypress/e2e/EnrollmentAddEventPage/EnrollmentAddEventPageForm/index.js
  src/core_modules/capture-core/components/WidgetEventSchedule/hooks/useCommentDetails.js
Labels: testing

#3434 feat: [DHIS-14012] removed download as XML button
  i18n/en.pot
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ViewMenuSetup/DownloadDialog/DownloadDialog.component.js
Labels: testing

#3415 chore: [TECH-1539] Use Capture-UI IconButton
  src/core_modules/capture-core/components/FeedbackBar/FeedbackBar.component.js
  src/core_modules/capture-core/components/ListView/ColumnSelector/ColumnSelector.component.js
  src/core_modules/capture-core/components/ListView/Main/ListViewMain.component.js
  src/core_modules/capture-core/components/ListView/Menu/ListViewMenu.component.js
  src/core_modules/capture-core/components/Pagination/withDefaultNavigation.js
  src/core_modules/capture-core/components/Section/SectionHeaderSimple.component.js
  src/core_modules/capture-ui/AgeField/AgeField.component.js
  src/core_modules/capture-ui/AgeField/ageField.module.css
  src/core_modules/capture-ui/CoordinateField/CoordinateField.component.js
  src/core_modules/capture-ui/CoordinateField/coordinateField.module.css
  src/core_modules/capture-ui/IconButton/IconButton.component.js
  src/core_modules/capture-ui/IconButton/iconButton.module.css
  src/core_modules/capture-ui/IconButton/iconButton.types.js
  src/core_modules/capture-ui/Icons/ChevronIcon.component.js
  src/core_modules/capture-ui/Icons/index.js
  src/core_modules/capture-ui/index.js
Labels: testing
