Repository dhis2/capture-app, pull requests merged in 2023-03, with the labels that each got.

#3175 fix: [DHIS2-13203] show default column when no displayInReports attributes are avai…
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/hooks/useDefaultColumnConfig.js
Labels: testing

#3166 fix: [DHIS2-14418] show only future events when filter by scheduled status
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getEventListData/getEventListData.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getEventListData/getScheduledDateQueryArgs.js
Labels: testing

#3165 feat: [DHIS2-14008] use the SelectionBar ui component inside ScopeSelector
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm.feature
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageForm/index.js
  cypress/integration/EnrollmentEditEventPage/EnrollmentEditEventPageNavigation/index.js
  cypress/integration/EnrollmentPage/EnrollmentPageNavigation/index.js
  cypress/integration/NewPage/index.js
  cypress/integration/ScopeSelector/index.js
  cypress/integration/SearchPage/index.js
  cypress/integration/TopBarActions/index.js
  cypress/integration/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard/index.js
  cypress/integration/WorkingLists/EventWorkingLists/EventWorkingListsUser/index.js
  cypress/integration/sharedSteps.js
  i18n/en.pot
  package.json
  src/core_modules/capture-core/components/FormFields/New/Fields/OrgUnitField/OrgUnitTree.component.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.component.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.container.js
  src/core_modules/capture-core/components/Pages/Enrollment/TopBar.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/TopBar/TopBar.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/TopBar.container.js
  src/core_modules/capture-core/components/Pages/MainPage/TopBar.container.js
  src/core_modules/capture-core/components/Pages/New/TopBar.container.js
  src/core_modules/capture-core/components/Pages/Search/TopBar.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/TopBar.container.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/FiltrableMenuItems/FiltrableMenuItems.container.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/FiltrableMenuItems/index.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/OrgUnitSelector.component.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/Program/CategorySelector.component.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/Program/EmptyPrograms.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/Program/ProgramList.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/Program/ProgramSelector.component.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/Program/getOptions.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/Program/programSelector.css
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/QuickSelector.component.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/QuickSelector.types.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/SingleLockedSelect.component.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/programSelector.css
  src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.component.js
  src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.container.js
  src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.types.js
  src/core_modules/capture-core/components/ScopeSelector/SingleLockedSelect/SingleLockedSelect.component.js
  src/core_modules/capture-core/components/ScopeSelector/SingleLockedSelect/index.js
  src/core_modules/capture-core/components/ScopeSelector/index.js
  src/core_modules/capture-core/components/TopBarActions/TopBarActions.component.js
  src/core_modules/capture-core/components/TopBarActions/TopBarActions.container.js
  src/core_modules/capture-core/components/TopBarActions/TopBarActions.types.js
  src/core_modules/capture-core/components/WidgetEnrollment/hooks/useEnrollment.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
  yarn.lock
Labels: testing

#3202 ci: no cache Cypress
  .github/workflows/e2e-tests.yml
  .github/workflows/verify-app.yml
Labels: testing

#3183 fix: [TECH-1499] hiding a section should not erase its fields
  src/core_modules/capture-core/components/D2Form/D2Section.component.js
  src/core_modules/capture-core/rules/postProcessRulesEffects.js
Labels: back-port

#3199 fix: [DHIS2-14845] crash on searching in all programs when enrollment not found
  src/core_modules/capture-core/components/CardList/CardListItem.component.js
Labels: awaiting RCB approval, testing

#3181 feat: [DHIS2-12337] indicate waiting on saving new tei
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.component.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.container.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.types.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.component.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/TeiRegistrationEntry.types.js
  src/core_modules/capture-core/components/Pages/New/EnrollmentRegistrationEntryWrapper.component.js
  src/core_modules/capture-core/components/Pages/New/NewPage.actions.js
  src/core_modules/capture-core/components/Pages/New/NewPage.component.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.actions.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.component.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.container.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
  src/core_modules/capture-core/reducers/descriptions/newPage.reducerDescription.js
Labels: testing
