Repository dhis2/capture-app, pull requests merged in 2023-04, with the labels that each got.

#3235 chore: non-mandatory dev-tests
  .github/workflows/verify-app.yml
Labels: e2e-tests

#3145 refactor: [TECH-1483] dataElements store in IndexedDB
  package.json
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/FormFoundation/types.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/common/factory/searchGroup/searchGroupFactory.types.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/programStage/DataElementFactory.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/programStage/ProgramStageFactory.js
  src/core_modules/capture-core/metaDataStoreLoaders/baseLoader/loadMetaDataInternal.js
  src/core_modules/capture-core/metaDataStoreLoaders/context/context.types.js
  src/core_modules/capture-core/metaDataStoreLoaders/dataElements/index.js
  src/core_modules/capture-core/metaDataStoreLoaders/dataElements/loadDataElements.js
  src/core_modules/capture-core/metaDataStoreLoaders/dataElements/quickStoreOperations/index.js
  src/core_modules/capture-core/metaDataStoreLoaders/dataElements/quickStoreOperations/storeDataElements.js
  src/core_modules/capture-core/metaDataStoreLoaders/programs/loadPrograms.js
  src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/storePrograms.js
  src/core_modules/capture-core/metaDataStoreLoaders/trackedEntityTypes/quickStoreOperations/storeTrackedEntityTypes.js
  src/core_modules/capture-core/storageControllers/cache.types.js
  src/core_modules/capture-core/storageControllers/index.js
  src/core_modules/capture-core/storageControllers/stores/userStores.const.js
Labels: e2e-tests

#3234 fix: [DHIS2-15109] eventDate breaks saved working lists
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/helpers/eventFilters/clientConfigToApiEventFilterQueryCriteriaConverter/convertToEventFilterEventQueryCriteria.js
Labels: testing

#3221 fix: [DHIS2-14976] apply input converters on context variables
  packages/rules-engine/src/services/VariableService/VariableService.js
Labels: testing

#3226 fix: [DHIS2-14868] extend the clickable zone for search header
  src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.component.js
Labels: skip-e2e-tests

#3227 fix: [DHIS2-14868] extend the clickable zone for search header v37
  package.json
  src/core_modules/capture-core/components/Pages/Search/SearchForm/SearchForm.component.js
  yarn.lock
Labels: preview

#3228 feat: [DHIS2-12256] use display label for due date and execution date
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.container.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.container.js
  src/core_modules/capture-core/components/WidgetEventSchedule/hooks/useScheduleConfigFromProgramStage.js
  src/core_modules/capture-core/components/WidgetEventSchedule/widgetEventSchedule.types.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/programStage/ProgramStageFactory.js
  src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/storePrograms.js
  src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/types/apiPrograms.types.js
  src/core_modules/capture-core/storageControllers/cache.types.js
Labels: skip-e2e-tests

#3232 chore: [DHIS2-7325] add alternate pattern for form
  src/core_modules/capture-core/components/DataEntry/DataEntry.component.js
  src/core_modules/capture-core/components/DataEntry/FieldSection.component.js
Labels: testing
