Repository dhis2/capture-app, pull requests merged in 2024-11, with the labels that each got.

#3848 fix: [DHIS2-18248] pass on createdAt to rules engine when editing
  packages/rules-engine/src/services/VariableService/variableService.types.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/epics/editEventDataEntry.epics.js
Labels: testing

#3868 fix: [DHIS2-18238] incorrect criteria when saving list with follow up false
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/programStageTemplates.epics.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/teiTemplates.epics.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/TEIFilters/clientConfigToApiTEIFilterQueryConverter/convertors.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/TemplateMaintenance/DeleteConfirmationDialog.component.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/TemplateMaintenance/ExistingTemplateContents.component.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsBase/TemplateMaintenance/NewTemplateContents.component.js
Labels: testing

#3858 fix: [DHIS2-17135][DHIS2-17018] Adjust strings for error messages
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/Enrollment/MissingMessage.component.js
  src/core_modules/capture-core/components/WidgetAssignee/DisplayMode.component.js
Labels: e2e-tests, testing

#3873 fix: [DHIS2-18278] remove completedAt and completedBy from the payload send to the API
  cypress/e2e/EnrollmentAddEventPage/EnrollmentAddEventPageForm/EnrollmentAddEventPageForm.js
  cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageForm/EnrollmentEditEventPageForm.js
  cypress/e2e/WidgetsForEnrollmentPages/WidgetEnrollment/index.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/getConvertedNewSingleEvent.js
  src/core_modules/capture-core/components/DataEntry/common/convertEventToServerValues.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/getConvertedAddEvent.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.epics.js
  src/core_modules/capture-core/events/mainConverters/mainEventClientToServerConverter.js
  src/core_modules/capture-core/events/mainConverters/mainEventConverter.js
Labels: testing

#3849 feat: [DHIS2-18250] Breadcrumb for event & enrollment pages
  cypress/e2e/EnrollmentAddEventPage/EnrollmentAddEventPageForm/EnrollmentAddEventPageForm.feature
  cypress/e2e/EnrollmentAddEventPage/EnrollmentAddEventPageNavigation/EnrollmentAddEventPageNavigation.feature
  cypress/e2e/EnrollmentAddEventPage/sharedSteps.js
  cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageForm/EnrollmentEditEventPageForm.feature
  cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageForm/EnrollmentEditEventPageForm.js
  cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageNavigation/EnrollmentEditEventPageNavigation.feature
  cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageNavigation/EnrollmentEditEventPageNavigation.js
  cypress/e2e/EnrollmentPage/EnrollmentPageNavigation/EnrollmentPageNavigation.js
  cypress/e2e/EnrollmentPage/EnrollmentQuickActions/EnrollmentQuickActions.js
  cypress/e2e/EnrollmentPage/sharedSteps.js
  cypress/e2e/ScopeSelector/ScopeSelector.feature
  cypress/e2e/ScopeSelector/ScopeSelector.js
  cypress/e2e/TopBarActions/TopBarActions.feature
  cypress/e2e/TopBarActions/TopBarActions.js
  cypress/e2e/WidgetsForEnrollmentPages/WidgetEventNote/index.js
  i18n/en.pot
  src/core_modules/capture-core/components/Breadcrumbs/EnrollmentBreadcrumb/EnrollmentBreadcrumb.js
  src/core_modules/capture-core/components/Breadcrumbs/EnrollmentBreadcrumb/hooks/useWorkingListLabel.js
  src/core_modules/capture-core/components/Breadcrumbs/EnrollmentBreadcrumb/index.js
  src/core_modules/capture-core/components/Breadcrumbs/EventBreadcrumb/EventBreadcrumb.js
  src/core_modules/capture-core/components/Breadcrumbs/EventBreadcrumb/hooks/useWorkingListLabel.js
  src/core_modules/capture-core/components/Breadcrumbs/EventBreadcrumb/index.js
  src/core_modules/capture-core/components/Breadcrumbs/common/BreadcrumbItem.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.container.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.types.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/ViewEvent.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/ViewEvent.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventPage.component.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/DefaultEnrollmentLayout.constants.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/EnrollmentPageLayout.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useSetProgramId.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
Labels: testing

#3837 fix: [DHIS2-16994] Image and File DE and TEA not Displayed in Changelog
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/EventDetailsSection.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/EventDetailsSection.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/EventChangelogWrapper/EventChangelogWrapper.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/EventChangelogWrapper/EventChangelogWrapper.types.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
  src/core_modules/capture-core/components/WidgetProfile/OverflowMenu/OverflowMenu.component.js
  src/core_modules/capture-core/components/WidgetProfile/OverflowMenu/OverflowMenu.container.js
  src/core_modules/capture-core/components/WidgetProfile/OverflowMenu/OverflowMenu.types.js
  src/core_modules/capture-core/components/WidgetProfile/OverflowMenu/TrackedEntityChangelogWrapper/TrackedEntityChangelogWrapper.component.js
  src/core_modules/capture-core/components/WidgetProfile/OverflowMenu/TrackedEntityChangelogWrapper/TrackedEntityChangelogWrapper.types.js
  src/core_modules/capture-core/components/WidgetProfile/WidgetProfile.component.js
  src/core_modules/capture-core/components/WidgetsChangelog/WidgetEventChangelog/WidgetEventChangelog.js
  src/core_modules/capture-core/components/WidgetsChangelog/WidgetTrackedEntityChangelog/WidgetTrackedEntityChangelog.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/Changelog/Changelog.container.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogTable/ChangelogCells/ChangelogValueCell.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogTable/ChangelogTableRow.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/hooks/index.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/hooks/useChangelogData.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/hooks/useListDataValues.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/utils/getSubValueForChangelogData.js
Labels: testing, e2e record

#3872 fix: [DHIS2-18019] related stages UI tweaks
  cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageForm/EnrollmentEditEventPageForm.js
  cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageNavigation/EnrollmentEditEventPageNavigation.js
  cypress/e2e/TopBarActions/TopBarActions.js
  cypress/e2e/WidgetsForEnrollmentPages/WidgetAssignee/index.js
  cypress/e2e/WidgetsForEnrollmentPages/WidgetEventNote/index.js
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentAddEventPage/WidgetsForEnrollmentAddEventPage.js
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard/WidgetsForEnrollmentDashboard.js
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/PageLayout/DefaultPageLayout.constants.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/DefaultEnrollmentLayout.types.js
  src/core_modules/capture-core/components/Pages/common/WidgetEventEditWrapper/WidgetEventEditWrapper.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetHeader/WidgetHeader.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetHeader/WidgetHeader.types.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetHeader/index.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/WidgetHeader/WidgetHeader.container.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/WidgetHeader/WidgetHeader.types.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/WidgetHeader/index.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/WidgetTwoEventWorkspace.container.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/WidgetTwoEventWorkspace.types.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/WidgetTwoEventWorkspaceWrapper.const.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/WidgetWrapper/WidgetWrapper.container.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/WidgetWrapper/WidgetWrapper.types.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/WidgetWrapper/index.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/index.js
Labels: testing

#3855 fix: [DHIS2-18150] user has to click out of range filter for update button to trigger
  src/core_modules/capture-core/components/FiltersForTypes/Numeric/NumericFilter.component.js
Labels: testing

#3781 fix: [DHIS2-17519] app crashing when opening new event from view event
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/SingleEventRegistrationEntry.component.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/SingleEventRegistrationEntry.container.js
Labels: testing

#3856 fix: [DHIS2-16801] events scheduled for today's date not showing today
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/hooks/helpers.js
Labels: e2e-tests, testing

#3712 feat: [DHIS2-15463] Use dhis2 ui calendarInput component in working list
  cypress/e2e/WorkingLists/EventWorkingLists/EventWorkingListsUser/EventWorkingListsUser.js
  package.json
  src/core_modules/capture-core/components/FiltersForTypes/Date/DateFilter.component.js
  src/core_modules/capture-core/components/FiltersForTypes/Date/DateFilterManager.component.js
  src/core_modules/capture-core/components/FiltersForTypes/Date/End.component.js
  src/core_modules/capture-core/components/FiltersForTypes/Date/From.component.js
  src/core_modules/capture-core/components/FiltersForTypes/Date/RangeFilter.component.js
  src/core_modules/capture-core/components/FiltersForTypes/Date/To.component.js
  src/core_modules/capture-core/components/FiltersForTypes/Date/dateFilterDataGetter.js
  src/core_modules/capture-core/components/FiltersForTypes/Date/types/date.types.js
  src/core_modules/capture-core/components/FiltersForTypes/Date/types/index.js
  src/core_modules/capture-core/components/FormFields/DateAndTime/D2Date/D2Date.component.js
  src/core_modules/capture-core/components/FormFields/DateAndTime/D2Date/D2DateCalendar.component.js
  src/core_modules/capture-core/components/FormFields/DateAndTime/D2Date/D2DatePopup.component.js
  src/core_modules/capture-core/components/FormFields/DateAndTime/D2Date/customStyles.css
  src/core_modules/capture-core/components/FormFields/DateAndTime/D2Date/d2DatePopup.const.js
  src/core_modules/capture-core/components/FormFields/DateAndTime/D2Date/getTheme.js
  src/core_modules/capture-core/components/FormFields/Options/FormGroup.component.js
  yarn.lock
Labels: e2e-tests, testing
