Repository dhis2/capture-app, pull requests merged in 2024-10, with the labels that each got.

#3788 fix: [DHIS2-18004] sort events in rules engine by occurredAt and createdAt
  packages/rules-engine/src/services/VariableService/VariableService.js
  packages/rules-engine/src/services/VariableService/helpers/structureEvents.js
  packages/rules-engine/src/services/VariableService/variableService.types.js
  src/core_modules/capture-core/rules/converters/dateUtils.js
Labels: testing

#3794 feat: [DHIS2-17874] replace remaining Material UI components
  i18n/en.pot
  src/core_modules/capture-core/components/FeedbackBar/FeedbackBar.component.js
  src/core_modules/capture-core/components/FormFields/UserField/SearchSuggestion.component.js
  src/core_modules/capture-core/components/IncompleteSelectionsMessage/index.js
  src/core_modules/capture-core/components/ListView/Filters/FilterButton/ActiveFilterButton.component.js
  src/core_modules/capture-core/components/ListView/Filters/FilterButton/FilterButtonMain.component.js
  src/core_modules/capture-core/components/ListView/Filters/FilterRestMenu/FilterRestMenu.component.js
  src/core_modules/capture-core/components/ListView/Menu/ListViewMenu.component.js
  src/core_modules/capture-core/components/ListView/types/listView.types.js
  src/core_modules/capture-core/components/ListView/withEndColumnMenu/RowMenu.component.js
  src/core_modules/capture-core/components/NetworkStatusBadge/NetworkStatusBadge.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/Section/ViewEventSection.component.js
  src/core_modules/capture-core/components/Popper/Popper.component.js
  src/core_modules/capture-core/components/Relationships/Relationships.component.js
  src/core_modules/capture-core/components/WidgetErrorAndWarning/WidgetError/WidgetErrorHeader.js
  src/core_modules/capture-core/components/WidgetErrorAndWarning/WidgetWarning/WidgetWarningHeader.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageOverview/StageOverview.component.js
  src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/NewTrackedEntityRelationship/hooks/useAddRelationship.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/RowMenuSetup/EventWorkingListsRowMenuSetup.component.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/RowMenuSetup/eventWorkingListsRowMenuSetup.types.js
  src/core_modules/capture-ui/Icons/DropdownChevron.component.js
  src/core_modules/capture-ui/Icons/index.js
Labels: testing

#3823 fix: [DHIS2-18116] check return value of `parseDate`
  src/core_modules/capture-core/converters/formToClient.js
Labels: testing

#3787 fix: [DHIS2-17530] show missing FILE url
  src/core_modules/capture-core/components/WidgetProfile/hooks/getSubValueForTei.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getEventListData/convertToClientEvents.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getListDataCommon/buildUrlByElementType.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getListDataCommon/getSubvalues.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getListDataCommon/index.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/convertToClientTeis.js
  src/core_modules/capture-core/trackedEntityInstances/getSubValues.js
Labels: testing

#3816 feat: [DHIS2-18081] Problem with date format when scheduling an event
  src/core_modules/capture-core/components/WidgetEventSchedule/ScheduleDate/ScheduleDate.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/ScheduleDate/scheduleDate.types.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.container.js
  src/core_modules/capture-core/components/WidgetEventSchedule/widgetEventSchedule.types.js
Labels: e2e-tests, testing

#3825 docs: [DHIS2-15238] show and filter on assigned user in program stage WL
  docs/user/using-the-capture-app.md
Labels: skip-e2e-tests

#3813 feat: [DHIS2-17771] Org unit context in tables and lists
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/getSubValueForTei.js
  src/core_modules/capture-core/components/Tooltips/TooltipOrgUnit/TooltipOrgUnit.component.js
  src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.component.js
  src/core_modules/capture-core/components/WidgetProfile/hooks/getSubValueForTei.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/hooks/helpers.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/hooks/useEventList.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/getEventDataWithSubValue.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/FlatListOrgUnitField/FlatListOrgUnitField.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/FlatListOrgUnitField/index.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/utils/getDataEntryDetails.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/utils/getSubValueForDataValue.js
  src/core_modules/capture-core/converters/clientToList.js
  src/core_modules/capture-core/converters/clientToView.js
  src/core_modules/capture-core/metadataRetrieval/orgUnitName/index.js
  src/core_modules/capture-core/metadataRetrieval/orgUnitName/orgUnitName.js
Labels: testing

#3795 fix: [DHIS2-18028] User is able to add invalid related stages event
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/getConvertedRelatedStageEvent/getConvertedRelatedStageEvent.js
  src/core_modules/capture-core/components/WidgetRelatedStages/LinkToExisting/LinkToExisting.component.js
  src/core_modules/capture-core/components/WidgetRelatedStages/LinkToExisting/LinkToExisting.types.js
  src/core_modules/capture-core/components/WidgetRelatedStages/RelatedStagesActions/RelatedStagesActions.component.js
  src/core_modules/capture-core/components/WidgetRelatedStages/RelatedStagesActions/RelatedStagesActions.types.js
  src/core_modules/capture-core/components/WidgetRelatedStages/WidgetRelatedStages.component.js
  src/core_modules/capture-core/components/WidgetRelatedStages/hooks/useCanAddNewEventToStage.js
  src/core_modules/capture-core/components/WidgetRelatedStages/hooks/useRelatedStageEvents.js
Labels: testing

#3843 test: cleanup after running NewPage tests
  cypress/e2e/NewPage/NewPage.feature
  cypress/e2e/NewPage/NewPage.js
Labels: e2e-tests

#3796 chore: [DHIS2-17915] remove opt-in functionality
  cypress/e2e/EnrollmentAddEventPage/EnrollmentAddEventPageForm/EnrollmentAddEventPageForm.feature
  cypress/e2e/EnrollmentPage/BreakingTheGlass/BreakingTheGlass.feature
  cypress/e2e/MainPage/MainPage.feature
  cypress/e2e/NewPage/NewPage.feature
  cypress/e2e/SearchPage/SearchPage.feature
  cypress/support/step_definitions/common/baseSteps.js
  docs/user/using-the-capture-app.md
  i18n/en.pot
  src/core_modules/capture-core/actions/navigateToEnrollmentOverview/navigateToEnrollmentOverview.constants.js
  src/core_modules/capture-core/actions/navigateToEnrollmentOverview/navigateToEnrollmentOverview.epics.js
  src/core_modules/capture-core/components/DataStore/DataStore.actions.js
  src/core_modules/capture-core/components/DataStore/DataStore.epics.js
  src/core_modules/capture-core/components/DataStore/DataStore.types.js
  src/core_modules/capture-core/components/DataStore/index.js
  src/core_modules/capture-core/components/OptInOut/OptIn/OptIn.component.js
  src/core_modules/capture-core/components/OptInOut/OptIn/OptIn.container.js
  src/core_modules/capture-core/components/OptInOut/OptIn/index.js
  src/core_modules/capture-core/components/OptInOut/OptIn/optIn.types.js
  src/core_modules/capture-core/components/OptInOut/OptOut/OptOut.component.js
  src/core_modules/capture-core/components/OptInOut/OptOut/OptOut.container.js
  src/core_modules/capture-core/components/OptInOut/OptOut/index.js
  src/core_modules/capture-core/components/OptInOut/OptOut/optOut.types.js
  src/core_modules/capture-core/components/OptInOut/index.js
  src/core_modules/capture-core/components/Pages/MainPage/WorkingListsType/WorkingListsType.component.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/helpers/getStageWithOpenAfterEnrollment.js
  src/core_modules/capture-core/components/Pages/ViewEvent/RightColumn/RelationshipsSection/ConnectedEntity/TrackedEntityInstance.js
  src/core_modules/capture-core/reducers/descriptions/useNewDashboard.reducerDescription.js
  src/core_modules/capture-core/utils/routing/index.js
  src/core_modules/capture-core/utils/routing/newDashboard.js
  src/epics/trackerCapture.epics.js
  src/reducers/descriptions/trackerCapture.reducerDescriptions.js
Labels: testing

#3838 fix: [DHIS2-18215] selected working list not persisted on navigate
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/TeiWorkingListsUser.feature
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/TeiWorkingListsUser.js
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/MainPage/MainPage.container.js
Labels: testing

#3798 feat: [DHIS2-17970] Auto-select orgUnit if there is only one available
  src/core_modules/capture-core/components/MetadataAutoSelectInitializer/hooks/useMetadataAutoSelect.js
  src/core_modules/capture-core/components/WidgetRelatedStages/WidgetRelatedStages.component.js
  src/core_modules/capture-core/dataQueries/index.js
  src/core_modules/capture-core/dataQueries/useOrgUnitsForAutoSelect.js
Labels: testing

#3827 fix: [DHIS2-16993] Text and long text DEs are missing arrows in changelog when deleted
  src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogTable/ChangelogChangeCell.js
Labels: testing

#3835 fix: [DHIS2-18056] use linkedEntityFormFoundation instead of the searchFormFoundation
  src/core_modules/capture-core/components/Pages/NewRelationship/TeiRelationship/SearchResults/TeiRelationshipSearchResults.component.js
Labels: testing

#3847 fix: [DHIS2-17978] use title instead of alt on missing icons
  cypress/e2e/MainPage/MainPage.js
  i18n/en.pot
  src/core_modules/capture-ui/NonBundledIcon/NonBundledIcon.component.js
Labels: testing

#3834 feat: [DHIS2-16992] Fixed size for changelog modal and columns
  i18n/en.pot
  src/core_modules/capture-core/components/WidgetsChangelog/common/Changelog/Changelog.component.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogTable/ChangelogCells/ChangelogChangeCell.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogTable/ChangelogCells/ChangelogValueCell.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogTable/ChangelogCells/index.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogTable/ChangelogTableHeader.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogTable/ChangelogTableRow.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogTable/index.js
Labels: e2e-tests, testing

#3828 feat: [DHIS2-17792] Org unit context in forms
  cypress/e2e/WidgetsForEnrollmentPages/WidgetEnrollment/index.js
  i18n/en.pot
  src/core_modules/capture-core/components/FormFields/New/Fields/OrgUnitField/SingleOrgUnitSelectField.component.js
  src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.component.js
Labels: e2e-tests, testing

#3765 fix: [DHIS2-16010] app crashes on invalid programid
  cypress/e2e/ScopeSelector/ScopeSelector.feature
  i18n/en.pot
  src/core_modules/capture-core/HOC/withErrorMessageHandler.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.component.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.container.js
  src/core_modules/capture-core/components/Pages/Enrollment/TopBar.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/TopBar.container.js
  src/core_modules/capture-core/components/Pages/MainPage/MainPage.component.js
  src/core_modules/capture-core/components/Pages/MainPage/MainPage.container.js
  src/core_modules/capture-core/components/Pages/MainPage/WithoutCategorySelectedMessage/WithoutCategorySelectedMessage.js
  src/core_modules/capture-core/components/Pages/MainPage/WithoutOrgUnitSelectedMessage/WithoutOrgUnitSelectedMessage.js
  src/core_modules/capture-core/components/Pages/MainPage/mainPage.types.js
  src/core_modules/capture-core/components/Pages/New/NewPage.component.js
  src/core_modules/capture-core/components/Pages/New/NewPage.container.js
  src/core_modules/capture-core/components/Pages/New/NewPage.types.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/RegistrationSection/RegUnitSelector/RegUnitSelector.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/epics/getCategoriesDataFromEvent.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/RegisterTei/RegistrationSection/RegUnitSelector/RegUnitSelector.component.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/QuickSelector.types.js
  src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.types.js
  src/core_modules/capture-core/components/TopBarActions/TopBarActions.types.js
  src/core_modules/capture-core/hooks/useProgramInfo/useProgramInfo.js
  src/core_modules/capture-core/metaData/helpers/getProgramEventAccess.js
Labels: testing

#3865 docs: improve docs
  docs/developer/configure-a-capture-plugin.mdx
  docs/developer/develop-a-capture-plugin.md
  docs/developer/enrollment-plugins/manual-setup.mdx
  docs/developer/form-field-plugins/developer-details.md
  docs/developer/getting-started.md
Labels: skip-e2e-tests

#3859 fix: [DHIS2-17843] Disable delete enrollment button when user does not have authority
  i18n/en.pot
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/Actions.component.js
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/Actions.container.js
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/Delete/Delete.component.js
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/Delete/delete.types.js
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/actions.types.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/hooks/index.js
  src/core_modules/capture-core/components/WidgetProfile/OverflowMenu/OverflowMenu.container.js
  src/core_modules/capture-core/components/WidgetProfile/OverflowMenu/hooks/index.js
  src/core_modules/capture-core/components/WidgetProfile/OverflowMenu/hooks/useAuthorities.js
  src/core_modules/capture-core/utils/authority/useAuthorities.js
Labels: e2e-tests, testing

#3857 fix: [DHIS2-18228] Image Deleted on Update
  src/core_modules/capture-core/events/getSubValues.js
Labels: testing

#3867 docs: [DHIS2-15187][DHIS2-15190] Working list bulk actions
  docs/user/resources/images/event-bulk-actions-selected-rows.png
  docs/user/resources/images/tracked-entity-bulk-actions-complete-enrollments.png
  docs/user/resources/images/tracked-entity-bulk-actions-delete-enrollments.png
  docs/user/resources/images/tracked-entity-bulk-actions-selected-rows.png
  docs/user/using-the-capture-app.md
Labels: skip-e2e-tests
