Repository dhis2/capture-app, pull requests merged in 2024-01, with the labels that each got.

#3500 fix: [DHIS2-16352] Add spacing between event overview cards
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/ViewEvent/RightColumn/RightColumnWrapper.component.js
Labels: testing

#3499 chore: [DHIS2] Upgrade DHIS2/ui to v9
  flow-typed/npm/@dhis2/ui_vx.x.x.js
  i18n/en.pot
  package.json
  yarn.lock
Labels: e2e-tests

#3482 fix: [DHIS2-15888] multi text element in program rules
  packages/rules-engine/src/commonUtils/normalizeRuleVariable.js
  packages/rules-engine/src/constants/typeKeys.const.js
  packages/rules-engine/src/constants/typeToInterfaceFnName.const.js
  packages/rules-engine/src/d2Functions/getD2Functions.js
  packages/rules-engine/src/d2Functions/getD2Functions.types.js
  packages/rules-engine/src/helpers/OptionSetHelper.js
  packages/rules-engine/src/rulesEngine.types.js
  packages/rules-engine/src/services/VariableService/VariableService.js
  packages/rules-engine/src/services/VariableService/index.js
  packages/rules-engine/src/services/VariableService/variableService.types.js
  src/core_modules/capture-core/components/FormFields/New/Fields/MultiSelectField/MultiSelectField.component.js
  src/core_modules/capture-core/components/FormFields/New/Fields/MultiSelectField/MultiSelectField.types.js
  src/core_modules/capture-core/rules/__tests__/postProcessRulesEffects.test.js
  src/core_modules/capture-core/rules/__tests__/ruleEffectsForEventProgram.test.js
  src/core_modules/capture-core/rules/__tests__/rulesEffectsForTrackerProgram.test.js
  src/core_modules/capture-core/rules/converters/inputConverter.js
  src/core_modules/capture-core/rules/converters/outputConverter.js
  src/core_modules/capture-core/rules/postProcessRulesEffects.js
Labels: testing

#3412 feat: [DHIS2-15480] widget assignee
  cypress/e2e/WidgetsForEnrollmentPages/WidgetAssignee/index.js
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent.feature
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent/index.js
  i18n/en.pot
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/getConvertedNewSingleEvent.js
  src/core_modules/capture-core/components/FormFields/UserField/index.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/NewEventWorkspace/NewEventWorkspace.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.actions.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/hooks/index.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/hooks/useAssignedUserSaveContext.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/index.js
  src/core_modules/capture-core/components/Pages/ViewEvent/RightColumn/AssigneeSection/AssigneeSection.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/RightColumn/AssigneeSection/AssigneeSection.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/RightColumn/AssigneeSection/Contents.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/RightColumn/AssigneeSection/DisplayMode.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/RightColumn/AssigneeSection/EditMode.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/RightColumn/AssigneeSection/assigneeSection.actions.js
  src/core_modules/capture-core/components/Pages/ViewEvent/RightColumn/AssigneeSection/index.js
  src/core_modules/capture-core/components/Pages/ViewEvent/RightColumn/AssigneeSection/saveAssignee.epic.js
  src/core_modules/capture-core/components/Pages/ViewEvent/RightColumn/RightColumnWrapper.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/ViewEvent.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/ViewEvent.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/viewEvent.actions.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/viewEvent.selectors.js
  src/core_modules/capture-core/components/Pages/ViewEvent/index.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/useCommonEnrollmentDomainData/useCommonEnrollmentDomainData.types.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/useRuleEffects/useRuleEffects.js
  src/core_modules/capture-core/components/WidgetAssignee/DisplayMode.component.js
  src/core_modules/capture-core/components/WidgetAssignee/EditMode.component.js
  src/core_modules/capture-core/components/WidgetAssignee/WidgetAssignee.component.js
  src/core_modules/capture-core/components/WidgetAssignee/WidgetAssignee.container.js
  src/core_modules/capture-core/components/WidgetAssignee/WidgetAssignee.types.js
  src/core_modules/capture-core/components/WidgetAssignee/converter.js
  src/core_modules/capture-core/components/WidgetAssignee/hooks/index.js
  src/core_modules/capture-core/components/WidgetAssignee/hooks/useUserAvatar.js
  src/core_modules/capture-core/components/WidgetAssignee/index.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/getConvertedAddEvent.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/widgetEventEdit.types.js
  src/core_modules/capture-core/components/WidgetEventSchedule/Assignee/Assignee.types.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.actions.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.container.js
  src/core_modules/capture-core/components/WidgetEventSchedule/widgetEventSchedule.types.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/hooks/useEvents.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/types/common.types.js
  src/core_modules/capture-core/converters/clientToServer.js
  src/core_modules/capture-core/converters/index.js
  src/core_modules/capture-core/converters/serverToClient.js
  src/core_modules/capture-core/events/eventRequests.js
  src/core_modules/capture-core/events/mainConverters/mainEventClientToServerConverter.js
  src/core_modules/capture-core/events/prepareEnrollmentEvents.js
  src/core_modules/capture-core/flow/apiTypes.js
  src/core_modules/capture-core/reducers/descriptions/enrollmentDomain.reducerDescription.js
  src/core_modules/capture-core/reducers/descriptions/feedback.reducerDescriptionGetter.js
  src/core_modules/capture-core/reducers/descriptions/viewEvent.reducerDescription.js
  src/epics/trackerCapture.epics.js
Labels: testing

#3508 feat: [DHIS2-16204] make opt-in to new dashboard the default
  cypress/e2e/EnrollmentAddEventPage/EnrollmentAddEventPageForm.feature
  cypress/e2e/EnrollmentAddEventPage/EnrollmentAddEventPageForm/index.js
  cypress/e2e/EnrollmentPage/BreakingTheGlass.feature
  cypress/e2e/EnrollmentPage/BreakingTheGlass/index.js
  cypress/e2e/MainPage.feature
  cypress/e2e/NewPage.feature
  cypress/e2e/NewPage/index.js
  cypress/e2e/SearchPage.feature
  cypress/e2e/SearchPage/index.js
  cypress/e2e/sharedSteps.js
  i18n/en.pot
  src/core_modules/capture-core/actions/navigateToEnrollmentOverview/navigateToEnrollmentOverview.actions.js
  src/core_modules/capture-core/actions/navigateToEnrollmentOverview/navigateToEnrollmentOverview.epics.js
  src/core_modules/capture-core/components/DataStore/DataStore.epics.js
  src/core_modules/capture-core/components/Pages/MainPage/MainPage.container.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
  src/core_modules/capture-core/components/Pages/ViewEvent/RightColumn/RelationshipsSection/ConnectedEntity/TrackedEntityInstance.js
  src/core_modules/capture-core/components/TrackerProgramHandler/TrackerProgramHandler.component.js
  src/core_modules/capture-core/components/TrackerProgramHandler/TrackerProgramHandler.container.js
  src/core_modules/capture-core/components/TrackerProgramHandler/index.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.epics.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/helpers/isNotValidOptionSet.js
  src/core_modules/capture-core/reducers/descriptions/useNewDashboard.reducerDescription.js
  src/core_modules/capture-core/utils/isNotValidOptionSet.js
  src/core_modules/capture-core/utils/routing/newDashboard.actions.js
  src/core_modules/capture-core/utils/routing/newDashboard.js
Labels: testing

#3502 feat: [DHIS2-15475] Form Field Plugins
  i18n/en.pot
  package.json
  src/core_modules/capture-core/components/D2Form/D2SectionFields.component.js
  src/core_modules/capture-core/components/D2Form/FormBuilder/FormBuilder.component.js
  src/core_modules/capture-core/components/D2Form/FormFieldPlugin/FormFieldPlugin.component.js
  src/core_modules/capture-core/components/D2Form/FormFieldPlugin/FormFieldPlugin.container.js
  src/core_modules/capture-core/components/D2Form/FormFieldPlugin/FormFieldPlugin.types.js
  src/core_modules/capture-core/components/D2Form/FormFieldPlugin/formatPluginConfig/formatPluginConfig.js
  src/core_modules/capture-core/components/D2Form/FormFieldPlugin/hooks/usePluginValues.js
  src/core_modules/capture-core/metaData/FormFieldPluginConfig/FormFieldPluginConfig.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/enrollment/EnrollmentFactory.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/trackedEntityTypes/factory/TrackedEntityType/TeiRegistrationFactory.js
  yarn.lock
Labels: testing

#3514 docs: [DHIS2-15480] assigned user widget for view and edit event
  docs/user/resources/images/user_assignment_edit.png
  docs/user/resources/images/user_assignment_edit_add.png
  docs/user/resources/images/user_assignment_edit_button.png
  docs/user/resources/images/user_assignment_edit_enrollment.png
  docs/user/using-the-capture-app.md
Labels: skip-e2e-tests

#3451 docs: [DHIS2-15483] assign user when reporting or scheduling an enrollment event
  docs/user/resources/images/user_assignment_report_new.png
  docs/user/resources/images/user_assignment_schedule_new_filled.png
  docs/user/using-the-capture-app.md
  i18n/en.pot
Labels: skip-e2e-tests
