Repository dhis2/capture-app, pull requests merged in 2024-08, with the labels that each got.

#3731 fix: [DHIS2-16373] cannot change AOC on existing events in Tracker program
  src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/viewEventDataEntry.actions.js
Labels: preview, testing

#3739 build: remove react-scripts 4.0.3 resolution
  .eslintrc
  .flowconfig
  cypress/support/cucumberPreprocessor.js
  package.json
  scripts/verifyCacheVersion.js
  src/core_modules/capture-core/components/D2Form/FormFieldPlugin/FormFieldPlugin.component.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentPlugin/EnrollmentPlugin.js
  src/core_modules/capture-core/trackerRedux/trackerReducer.js
  yarn.lock
Labels: e2e-tests

#3737 fix: [DHIS2-17516] bad request when sorting in the working lists
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/getEventListData.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/index.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getEventListData/getColumnsQueryArgs.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getEventListData/getEventListData.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getListDataCommon/getOrderQueryArgs.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getListDataCommon/index.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/getTeiListData.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/index.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/index.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/TEIFilters/apiTEIFilterToClientConfigConverter/convertSortToClient.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/templates/buildArgumentsForTemplate.js
Labels: testing

#3713 feat: [DHIS2-17648] Replace Material UI FormGroup, FormLabel and FormControl
  src/core_modules/capture-core/components/FormFields/Generic/D2TrueOnly.component.js
  src/core_modules/capture-core/components/FormFields/Options/FormGroup.component.js
  src/core_modules/capture-core/components/FormFields/Options/MultiSelectBoxes/MultiSelectBoxes.component.js
  src/core_modules/capture-core/components/FormFields/Options/SingleSelectBoxes/SingleSelectBoxes.component.js
  src/core_modules/capture-core/components/FormFields/Options/SingleSelectBoxes/singleSelectBoxes.types.js
Labels: testing

#3741 refactor: [DHIS2-17826] Replace Material UI Chip
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/ViewEvent/Section/ViewEventSectionHeader.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
Labels: e2e-tests, testing

#3735 feat: [DHIS2-16125] hide program stage under certain circumstances
  cypress/e2e/EnrollmentPage/HiddenProgramStage/HiddenProgramStage.feature
  cypress/e2e/EnrollmentPage/HiddenProgramStage/HiddenProgramStage.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/Stage.component.js
Labels: testing

#3684 feat: [DHIS2-17591][DHIS2-17607] Plugins in event forms
  i18n/en.pot
  src/core_modules/capture-core/components/D2Form/D2Form.component.js
  src/core_modules/capture-core/components/D2Form/D2SectionFields.component.js
  src/core_modules/capture-core/components/D2Form/FormBuilder/FormBuilder.component.js
  src/core_modules/capture-core/components/D2Form/FormFieldPlugin/FormFieldPlugin.const.js
  src/core_modules/capture-core/components/D2Form/FormFieldPlugin/FormFieldPlugin.container.js
  src/core_modules/capture-core/components/D2Form/FormFieldPlugin/FormFieldPlugin.types.js
  src/core_modules/capture-core/components/D2Form/FormFieldPlugin/hooks/usePluginCallbacks.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/DataEntry.container.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/NewEventDataEntryWrapper.component.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/NewEventDataEntryWrapper.container.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/NewEventDataEntryWrapper.types.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/newEventDataEntryWrapper.selectors.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/useRulesEngine.js
  src/core_modules/capture-core/components/DataEntries/common/ProgramStage/buildProgramStageMetadata.js
  src/core_modules/capture-core/components/DataEntries/common/ProgramStage/index.js
  src/core_modules/capture-core/components/DataEntries/common/ProgramStage/useDataElementsForStage.js
  src/core_modules/capture-core/components/DataEntries/common/ProgramStage/useMetadataForProgramStage.js
  src/core_modules/capture-core/components/DataEntries/common/TEIAndEnrollment/index.js
  src/core_modules/capture-core/components/DataEntries/common/TEIAndEnrollment/useMetadataForRegistrationForm/index.js
  src/core_modules/capture-core/components/DataEntries/common/TEIAndEnrollment/useMetadataForRegistrationForm/useMetadataForRegistrationForm.js
  src/core_modules/capture-core/components/DataEntries/index.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.types.js
  src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/EventDetailsSection.component.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/LayoutComponentConfig/LayoutComponentConfig.js
  src/core_modules/capture-core/components/Pages/common/WidgetEventEditWrapper/WidgetEventEditWrapper.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/WidgetEnrollmentEventNew.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/widgetEventEdit.types.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/enrollment/EnrollmentFactory.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/programStage/DataElementFactory.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/programStage/ProgramStageFactory.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/programStage/programStageFactory.types.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/trackedEntityTypes/factory/TrackedEntityType/TeiRegistrationFactory.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/trackedEntityTypes/factory/TrackedEntityType/teiRegistrationFactory.types.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/trackedEntityTypes/factory/TrackedEntityType/trackedEntityTypeFactory.types.js
Labels: testing

#3709 feat: [DHIS2-17726] Plugins in Profile Widget
  src/core_modules/capture-core/components/D2Form/FormFieldPlugin/FormFieldPlugin.const.js
  src/core_modules/capture-core/components/DataEntries/common/TEIAndEnrollment/index.js
  src/core_modules/capture-core/components/DataEntries/common/TEIAndEnrollment/useMetadataForRegistrationForm/index.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/DataEntry.container.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/FormFoundation/RenderFoundation.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/FormFoundation/types.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/dataEntry.types.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/hooks/useFormFoundation.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/hooks/useLifecycle.js
  src/core_modules/capture-core/components/WidgetProfile/WidgetProfile.component.js
  src/core_modules/capture-core/metaData/FormFieldPluginConfig/FormFieldPluginConfig.js
Labels: testing

#3748 fix: [DHIS2-17859] Add missing ids to Enrollment plugin
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/renderPageComponents/renderPageComponents.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentPlugin/EnrollmentPlugin.js
Labels: e2e-tests

#3694 feat: [DHIS2-17171] preview images in versions prior to 41
  src/core_modules/capture-core/components/WidgetProfile/hooks/getSubValueForTei.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/getEventDataWithSubValue.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getEventListData/convertToClientEvents.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getListDataCommon/getSubvalues.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/convertToClientTeis.js
  src/core_modules/capture-core/converters/clientToList.js
  src/core_modules/capture-core/converters/clientToView.js
  src/core_modules/capture-core/events/getSubValues.js
  src/core_modules/capture-core/trackedEntityInstances/getSubValues.js
Labels: testing

#3747 refactor: [DHIS2-17839] replace material ui Paper for Card
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/RecentlyAddedEventsList/RecentlyAddedEventsList.component.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/NewRelationshipWrapper/NewEventNewRelationshipWrapper.component.js
  src/core_modules/capture-core/components/ListView/Filters/FilterRestMenu/FilterRestMenu.component.js
  src/core_modules/capture-core/components/ListView/Menu/ListViewMenu.component.js
  src/core_modules/capture-core/components/ListView/withEndColumnMenu/RowMenu.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/Relationship/ViewEventNewRelationshipWrapper.component.js
Labels: testing

#3745 refactor: [DHIS2-17825] replace ClickAwayListener with Layer onBackdropClick
  cypress/e2e/WorkingLists/EventWorkingLists/EventWorkingListsUser/EventWorkingListsUser.js
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/TeiWorkingListsUser.js
  src/core_modules/capture-core/components/ListView/Filters/FilterRestMenu/FilterRestMenu.component.js
  src/core_modules/capture-core/components/ListView/withEndColumnMenu/RowMenu.component.js
  src/core_modules/capture-core/components/Popper/Popper.component.js
Labels: testing

#3718 refactor: [DHIS2-17750] replace material ui Card for Widget
  i18n/en.pot
  src/core_modules/capture-core/components/DataEntry/DataEntry.component.js
  src/core_modules/capture-core/components/DataEntry/dataEntryOutput/withDataEntryOutput.js
  src/core_modules/capture-core/components/DataEntry/dataEntryOutput/withErrorOutput.js
  src/core_modules/capture-core/components/DataEntry/dataEntryOutput/withFeedbackOutput.js
  src/core_modules/capture-core/components/DataEntry/dataEntryOutput/withIndicatorOutput.js
  src/core_modules/capture-core/components/DataEntry/dataEntryOutput/withWarningOutput.js
  src/core_modules/capture-core/components/WidgetFeedback/WidgetFeedback.component.js
  src/core_modules/capture-core/components/WidgetFeedback/WidgetFeedback.types.js
  src/core_modules/capture-core/components/WidgetFeedback/index.js
Labels: testing

#3738 fix: [DHIS2-17632][DHIS2-17633] restrict invalid category combo for orgUnit
  i18n/en.pot
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/DataEntry.component.js
  src/core_modules/capture-core/components/Pages/MainPage/InvalidCategoryCombinationForOrgUnitMessage/InvalidCategoryCombinationForOrgUnitMessage.js
  src/core_modules/capture-core/components/Pages/MainPage/MainPage.component.js
  src/core_modules/capture-core/components/Pages/MainPage/MainPage.constants.js
  src/core_modules/capture-core/components/Pages/MainPage/MainPage.container.js
  src/core_modules/capture-core/components/Pages/New/NewPage.actions.js
  src/core_modules/capture-core/components/Pages/New/NewPage.component.js
  src/core_modules/capture-core/components/Pages/New/NewPage.constants.js
  src/core_modules/capture-core/components/Pages/New/NewPage.container.js
  src/core_modules/capture-core/components/Pages/New/NewPage.types.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/Validated.container.js
  src/core_modules/capture-core/hooks/useCategoryComboIsValidForOrgUnit.js
  src/core_modules/capture-core/reducers/descriptions/newPage.reducerDescription.js
Labels: testing

#3719 refactor: [DHIS2-17652] Replace Material-UI Avatar
  src/core_modules/capture-core/components/CardList/CardListItem.component.js
  src/core_modules/capture-ui/CardImage/CardImage.component.js
Labels: e2e-tests, testing

#3721 refactor: [DHIS2-17650] Replace Material-UI Table, TableBody, TableCell, TableHead and TableRow
  cypress/e2e/AllAccessibleRecordsPage/AllAccessibleRecordsPage.js
  cypress/e2e/WorkingLists/EventWorkingLists/EventWorkingListsUser/EventWorkingListsUser.js
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/TeiWorkingListsUser.js
  i18n/en.pot
  src/core_modules/capture-core/components/ListView/ColumnSelector/DragDropList/DragDropList.component.js
  src/core_modules/capture-core/components/ListView/ColumnSelector/DragDropList/DragDropListItem.component.js
Labels: e2e-tests, testing

#3750 feat: [DHIS2-12288] add enrollment section description
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/FormFoundation/RenderFoundation.js
  src/core_modules/capture-core/components/WidgetProfile/hooks/useApiProgram.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/enrollment/EnrollmentFactory.js
  src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/storePrograms.js
  src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/types/apiPrograms.types.js
  src/core_modules/capture-core/storageControllers/cache.types.js
Labels: testing

#3754 fix: [DHIS2-17352] Changing program in event workspace does nothing
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/Program/ProgramSelector.component.js
Labels: testing

#3755 chore(release): stop support for 2.38
  cypress/e2e/EnrollmentPage/StagesAndEventsWidget/StagesAndEventsWidget.feature
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/TeiWorkingListsUser.feature
  d2.config.js
  src/core_modules/capture-core-utils/featuresSupport/support.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/hooks/useProgramStageFilters.js
Labels: e2e-tests

#3726 feat: [DHIS2-17655] Two event workspace
  i18n/en.pot
  src/core_modules/capture-core/components/Buttons/OverflowButton.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/PageLayout/DefaultPageLayout.constants.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/DefaultEnrollmentLayout.types.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/EnrollmentPageLayout.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/LayoutComponentConfig/LayoutComponentConfig.js
  src/core_modules/capture-core/components/Pages/common/WidgetEventEditWrapper/WidgetEventEditWrapper.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/FlatListOrgUnitField/FlatListOrgUnitField.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/FlatListOrgUnitField/index.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/WidgetTwoEventWorkspace.component.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/WidgetTwoEventWorkspace.container.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/WidgetTwoEventWorkspace.types.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/hooks/useClientDataValues.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/hooks/useLinkedEventByOriginId.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/index.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/utils/getDataEntryDetails.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/utils/getSubValueForDataValue.js
Labels: testing

#3706 fix: [DHIS2-17101] Consider prevent adding events to stage program rule
  src/core_modules/capture-core/components/WidgetRelatedStages/RelatedStagesActions/RelatedStagesActions.component.js
  src/core_modules/capture-core/components/WidgetRelatedStages/hooks/useCanAddNewEventToStage.js
Labels: e2e-tests, testing

#3757 refactor: [DHIS2-17860] replace material ui TextField for Input
  i18n/en.pot
  src/core_modules/capture-core/components/FiltersForTypes/Date/End.component.js
  src/core_modules/capture-core/components/FiltersForTypes/Date/Start.component.js
  src/core_modules/capture-core/components/FormFields/AgeField/AgeField.component.js
  src/core_modules/capture-core/components/FormFields/EmailField/EmailField.component.js
  src/core_modules/capture-core/components/FormFields/Generic/D2TextField.component.js
  src/core_modules/capture-core/components/FormFields/PhoneNumber/PhoneNumber.component.js
Labels: testing

#3763 refactor: [DHIS2-17840]replace Material UI Grid
  src/core_modules/capture-core/components/CardList/CardListItem.component.js
  src/core_modules/capture-core/components/IncompleteSelectionsMessage/index.js
  src/core_modules/capture-core/components/InfoIconText/InfoIconText.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.component.js
Labels: testing

#3751 feat: [DHIS2-17575] disable create new buttons if no data write access
  cypress/e2e/EnrollmentAddEventPage/ProgramStageSelector/ProgramStageSelector.feature
  cypress/e2e/EnrollmentAddEventPage/ProgramStageSelector/ProgramStageSelector.js
  cypress/e2e/EnrollmentPage/EnrollmentQuickActions/EnrollmentQuickActions.feature
  cypress/e2e/EnrollmentPage/EnrollmentQuickActions/EnrollmentQuickActions.js
  cypress/e2e/EnrollmentPage/StagesAndEventsWidget/StagesAndEventsWidget.feature
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentQuickActions/EnrollmentQuickActions.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/ProgramStageSelector/ProgramStageSelector.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/ProgramStageSelector/ProgramStageSelector.container.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/Stage.component.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageCreateNewButton/StageCreateNewButton.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageCreateNewButton/index.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js
Labels: testing

#3768 chore: [DHIS2-17925] adapt the transfer scenario to the newly added API restrictions
  cypress/e2e/WidgetsForEnrollmentPages/WidgetEnrollment/index.js
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard/WidgetsForEnrollmentDashboard.feature
Labels: e2e-tests

#3774 fix: [DHIS2-17953] Invalid dateFormat conversion in related stages
  src/core_modules/capture-core-utils/validators/form/date.validator.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/getConvertedRelatedStageEvent/getConvertedRelatedStageEvent.js
  src/core_modules/capture-core/utils/converters/date/stringToMomentDateFormat.js
Labels: testing

#3759 feat: [DHIS2-11836] respect block entry form
  cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageForm/EnrollmentEditEventPageForm.feature
  cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageForm/EnrollmentEditEventPageForm.js
  i18n/en.pot
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/constants/status.const.js
  src/core_modules/capture-core/components/WidgetEventEdit/hooks/index.js
  src/core_modules/capture-core/components/WidgetEventEdit/hooks/useAuthorities.js
  src/core_modules/capture-core/metaData/Program/ProgramStage.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/programStage/ProgramStageFactory.js
  src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/storePrograms.js
  src/core_modules/capture-core/storageControllers/cache.types.js
Labels: preview, testing

#3767 fix: [DHIS2-17651] enrollment dashboard UI changes
  cypress/e2e/EnrollmentAddEventPage/EnrollmentAddEventPageForm/EnrollmentAddEventPageForm.js
  cypress/e2e/EnrollmentPage/StagesAndEventsWidget/StagesAndEventsWidget.feature
  cypress/e2e/EnrollmentPage/StagesAndEventsWidget/StagesAndEventsWidget.js
  i18n/en.pot
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/Stage.component.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageOverview/StageOverview.component.js
Labels: testing
