Repository dhis2/capture-app, pull requests merged in 2024-09, with the labels that each got.

#3776 fix: [DHIS2-17971] trigger program stage specific rules on opening new event page
  src/core_modules/capture-core/components/DataEntries/common/ProgramStage/buildProgramStageMetadata.js
Labels: testing

#3756 feat: [DHIS2-17878][DHIS2-17048] Add overflow menu with actions to stages&events
  cypress/e2e/EnrollmentPage/StagesAndEventsWidget/StagesAndEventsWidget.feature
  cypress/e2e/EnrollmentPage/StagesAndEventsWidget/StagesAndEventsWidget.js
  i18n/en.pot
  src/core_modules/capture-core/components/Buttons/OverflowButton.component.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.container.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/LayoutComponentConfig/LayoutComponentConfig.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/enrollment.actions.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/useCommonEnrollmentDomainData/useCommonEnrollmentDomainData.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/EventRow/DeleteActionButton/DeleteActionButton.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/EventRow/DeleteActionButton/index.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/EventRow/DeleteActionModal/DeleteActionModal.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/EventRow/DeleteActionModal/index.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/EventRow/EventRow.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/EventRow/EventRow.types.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/EventRow/SkipAction/SkipAction.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/EventRow/SkipAction/index.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/EventRow/index.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/stageDetail.types.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/stage.types.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/stages.types.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/stagesAndEvents.types.js
  src/core_modules/capture-core/reducers/descriptions/enrollmentDomain.reducerDescription.js
Labels: testing

#3785 chore(deps): revert actions/download-artifact from 4.1.7 to 2 in /.github/workflows
  .github/workflows/verify-app.yml
Labels: e2e-tests

#3800 refactor: bump download-artifact and upload-artifact version
  .github/workflows/verify-app.yml
Labels: skip-e2e-tests

#3797 docs: [DHIS2-18052] Rebuild developer docs when there are changes
  .github/workflows/rebuild-docs.yml
  docs/developer/enrollment-plugins/manual-setup.mdx
Labels: skip-e2e-tests

#3814 feat: support custom background color
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/DefaultEnrollmentLayout.types.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/EnrollmentPageLayout.js
  src/core_modules/capture-core/components/Widget/WidgetCollapsible.component.js
Labels: e2e-tests
