Repository dhis2/capture-app, pull requests merged in 2024-02, with the labels that each got.

#3517 fix: [DHIS2-16499] Handle different API response format
  cypress/e2e/EnrollmentPage/BreakingTheGlass/index.js
  cypress/e2e/WorkingLists/EventWorkingLists/EventWorkingListsDev/index.js
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsDev/index.js
  src/core_modules/capture-core-utils/featuresSupport/support.js
  src/core_modules/capture-core/components/WidgetEventSchedule/hooks/useEventsInOrgUnit.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/FormFoundation/DataElement.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/helpers/handleAPIResponse.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/helpers/index.js
  src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/NewTrackedEntityRelationship/hooks/useAddRelationship.js
  src/core_modules/capture-core/components/WidgetsRelationship/common/useRelationships/useRelationships.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/getEventListData.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getEventListData/getEventListData.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/getTeiListData.js
  src/core_modules/capture-core/events/eventRequests.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/enrollment/DataElementFactory.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/trackedEntityTypes/factory/TrackedEntityType/DataElementFactory.js
  src/core_modules/capture-core/relationships/relationshipRequests.js
  src/core_modules/capture-core/trackedEntityInstances/trackedEntityInstanceRequests.js
  src/core_modules/capture-core/utils/api/handleAPIResponse.js
  src/core_modules/capture-core/utils/api/index.js
Labels: testing

#3481 feat: [DHIS2-16262] Support Custom Layout for Enrollment Pages
  cypress/e2e/ScopeSelector/index.js
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.component.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/DefaultPageLayout/DefaultPageLayout.constants.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/DefaultPageLayout/index.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.component.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.container.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/NewEventWorkspace/NewEventWorkspace.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/NewEventWorkspace/newEventWorkspace.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/PageLayout/DefaultPageLayout.constants.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.constants.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/PageLayout/DefaultPageLayout.constants.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/AddRelationshipRefWrapper/AddRelationshipRefWrapper.component.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/AddRelationshipRefWrapper/index.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/DefaultEnrollmentLayout.constants.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/DefaultEnrollmentLayout.types.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/EnrollmentPageLayout.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/LayoutComponentConfig/LayoutComponentConfig.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/LayoutComponentConfig/index.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/hooks/useEnrollmentPageLayout.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/hooks/useWidgetColumns.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/index.js
  src/core_modules/capture-core/components/Pages/common/NewEventWorkspaceWrapper/NewEventWorkspaceWrapper.js
  src/core_modules/capture-core/components/Pages/common/NewEventWorkspaceWrapper/index.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/TrackedEntityRelationshipsWrapper/TrackedEntityRelationshipsWrapper.types.js
  src/core_modules/capture-core/components/Pages/common/WidgetEventEditWrapper/WidgetEventEditWrapper.js
  src/core_modules/capture-core/components/Pages/common/WidgetEventEditWrapper/index.js
  src/core_modules/capture-core/components/WidgetErrorAndWarning/WidgetError/WidgetError.component.js
  src/core_modules/capture-core/components/WidgetErrorAndWarning/WidgetError/WidgetError.types.js
  src/core_modules/capture-core/components/WidgetErrorAndWarning/WidgetWarning/WidgetWarning.component.js
  src/core_modules/capture-core/components/WidgetErrorAndWarning/WidgetWarning/WidgetWarning.types.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/widgetEventEdit.types.js
  src/core_modules/capture-core/components/WidgetFeedback/WidgetFeedback.component.js
  src/core_modules/capture-core/components/WidgetFeedback/WidgetFeedback.types.js
  src/core_modules/capture-core/components/WidgetProfile/WidgetProfile.component.js
  src/core_modules/capture-core/components/WidgetProfile/widgetProfile.types.js
  src/core_modules/capture-core/utils/cachedDataHooks/useValidatedIDsFromCache.js
Labels: testing

#3515 feat: [DHIS2-16305] Enrollment Overview Plugins
  src/core_modules/capture-core/components/DataEntries/common/TEIAndEnrollment/useMetadataForRegistrationForm/hooks/useDataEntryFormConfig.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/DefaultEnrollmentLayout.types.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/hooks/useWidgetColumns.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/renderPageComponents/index.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/renderPageComponents/renderPageComponents.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentPlugin/EnrollmentPlugin.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentPlugin/index.js
Labels: testing

#3490 chore: fix cypress script command
  package.json
Labels: skip-e2e-tests

#3528 feat: [DHIS2-16745] dynamic naming to relationship widget
  i18n/en.pot
  src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/NewTrackedEntityRelationship/Breadcrumbs/Breadcrumbs.component.js
  src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/NewTrackedEntityRelationship/Breadcrumbs/breadcrumbs.types.js
  src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/NewTrackedEntityRelationship/NewTrackedEntityRelationship.component.js
  src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/NewTrackedEntityRelationship/NewTrackedEntityRelationship.container.js
  src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/NewTrackedEntityRelationship/NewTrackedEntityRelationship.types.js
  src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/WidgetTrackedEntityRelationship.component.js
  src/core_modules/capture-core/components/WidgetsRelationship/WidgetTrackedEntityRelationship/hooks/useTrackedEntityTypeName.js
Labels: testing

#3498 feat: [DHIS2-12007] Text String Improvements
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/ViewEvent/RightColumn/FeedbacksSection/FeedbacksSection.component.js
Labels: preview, e2e-tests

#3530 feat: [DHIS2-16527] assign user on first stage registration
  i18n/en.pot
  src/core_modules/capture-core/components/DataEntries/Enrollment/EnrollmentWithFirstStageDataEntry/EnrollmentWithFirstStageDataEntry.component.js
  src/core_modules/capture-core/components/DataEntries/Enrollment/EnrollmentWithFirstStageDataEntry/EnrollmentWithFirstStageDataEntry.constants.js
  src/core_modules/capture-core/components/DataEntries/Enrollment/EnrollmentWithFirstStageDataEntry/getDataEntryPropsToInclude.js
  src/core_modules/capture-core/components/DataEntries/Enrollment/EnrollmentWithFirstStageDataEntry/hooks/useDataEntrySections.js
  src/core_modules/capture-core/components/DataEntries/Enrollment/actions/open.actionBatchs.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/useBuildEnrollmentPayload.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/Assignee/Assignee.component.js
  src/core_modules/capture-core/components/DataEntry/common/convertDataEntryValuesToClientValues.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/helpers/deriveFirstStageDuringRegistrationEvent.js
Labels: testing

#3522 fix: [DHIS2-16318] enrollment page url management
  cypress/e2e/EnrollmentPage/BreakingTheGlass.feature
  cypress/e2e/EnrollmentPage/EnrollmentPageNavigation.feature
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.actions.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.constants.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.container.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.epics.js
  src/core_modules/capture-core/components/Pages/Enrollment/useEnrollmentInfo.js
  src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.container.js
  src/core_modules/capture-core/reducers/descriptions/activePage.reducerDescription.js
  src/core_modules/capture-core/reducers/descriptions/enrollmentPage.reducerDescription.js
  src/epics/trackerCapture.epics.js
Labels: testing
