Repository dhis2/capture-app, pull requests merged in 2024-05, with the labels that each got.

#3643 fix: [DHIS2-17399] use server version to send correct aoc payload
  src/core_modules/capture-core-utils/featuresSupport/support.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/useBuildEnrollmentPayload.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/getConvertedNewSingleEvent.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/saveNewSingleEvent.epics.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/saveNewSingleEventAddAnother.epics.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/saveNewSingleEventStage.epics.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.container.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/helpers/deriveAutoGenerateEvents.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/helpers/deriveFirstStageDuringRegistrationEvent.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/ViewEvent.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/viewEvent.selectors.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventPage.component.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/getConvertedAddEvent.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/useBuildNewEventPayload.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.epics.js
  src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/viewEventDataEntry.actions.js
  src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/viewEventDataEntry.epics.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.epics.js
  src/core_modules/capture-core/converters/clientToServer.js
  src/core_modules/capture-core/events/convertEventAttributeOptions.js
  src/core_modules/capture-core/events/mainConverters/mainEventClientToServerConverter.js
Labels: testing, RCB approved

#3649 docs: [DHIS2-15633] change comment to note docs
  docs/user/resources/images/enrollment-widget-comment.png
  docs/user/resources/images/enrollment-widget-note.png
  docs/user/resources/images/schedule_event_02.png
  docs/user/resources/images/schedule_event_04.png
  docs/user/using-the-capture-app.md
Labels: e2e-tests

#3583 fix: [DHIS2-17089] replace "Registering unit" text with "Organisation unit" text
  cypress/e2e/NewPage/index.js
  cypress/e2e/ScopeSelector/index.js
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
  docs/user/using-the-capture-app.md
  i18n/en.pot
  src/core_modules/capture-core/components/LockedSelector/LockedSelector.epics.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.component.js
  src/core_modules/capture-core/components/Pages/New/NewPage.component.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/TeiSearch/SearchOrgUnitSelector/searchOrgUnitSelector.epics.js
  src/core_modules/capture-core/components/Pages/common/WidgetEventEditWrapper/WidgetEventEditWrapper.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/OrgUnitSelector.component.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/Program/ProgramList.js
  src/core_modules/capture-core/components/TeiSearch/SearchOrgUnitSelector/searchOrgUnitSelector.epics.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/hooks/useEventList.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/hooks/useDefaultColumnConfig.js
Labels: testing

#3633 fix: [DHIS2-17291][DHIS2-16597] skip trackedEntites request when no events match the WL filters
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getEventListData/getEventListData.js
Labels: testing

#3629 fix: [DHIS2-15920] skip duplicates reviews
  src/core_modules/capture-core/components/DataEntries/common/TEIAndEnrollment/geometry.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/TrackedEntityInstance/DataEntryTrackedEntityInstance.component.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/RegisterTei/DataEntry/TrackedEntityInstance/DataEntryTrackedEntityInstance.js
  src/core_modules/capture-core/components/PossibleDuplicatesDialog/possibleDuplicatesDialog.actions.js
  src/core_modules/capture-core/components/PossibleDuplicatesDialog/possibleDuplicatesDialog.epics.js
  src/core_modules/capture-core/reducers/descriptions/possibleDuplicates.reducerDescription.js
Labels: testing

#3592 fix: [DHIS2-17102] edit event navigation
  cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageForm.feature
  cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageForm/index.js
  cypress/e2e/ViewPage/EditEventPageForm.feature
  cypress/e2e/ViewPage/EditEventPageForm/index.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/EventDetailsSection.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/ViewEvent.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/viewEvent.actions.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.actions.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.epics.js
  src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/viewEventDataEntry.epics.js
  src/core_modules/capture-core/reducers/descriptions/viewEvent.reducerDescription.js
Labels: testing

#3605 fix: [DHIS2-17052] Unrelated error message on no TETs
  i18n/en.pot
  src/core_modules/capture-core/components/TrackedEntityTypeSelector/TrackedEntityTypeSelector.component.js
Labels: testing
