Repository dhis2/capture-app, pull requests merged in 2024-06, with the labels that each got.

#3659 chore: [DHIS2-17372] reduce test groups to 5 for improved CI performance
  .github/workflows/e2e-tests.yml
  .github/workflows/verify-app.yml
  cypress/support/generateTestMatrix.js
Labels: e2e-tests

#3619 fix: [DHIS2-17249] remove the option to download TEIs when no orgUnit is selected
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/ViewMenuSetup/TrackerWorkingListsViewMenuSetup.component.js
Labels: testing

#3604 fix: [DHIS2-16487] Auto-select program and org-unit
  src/components/App/App.component.js
  src/core_modules/capture-core/components/MetadataAutoSelectInitializer/MetadataAutoSelectInitializer.js
  src/core_modules/capture-core/components/MetadataAutoSelectInitializer/hooks/useMetadataAutoSelect.js
  src/core_modules/capture-core/components/MetadataAutoSelectInitializer/index.js
Labels: testing

#3550 fix: [DHIS2-15379] Misaligned Data elements in TET profile
  src/core_modules/capture-ui/FlatList/FlatList.component.js
Labels: testing

#3664 refactor: [DHIS2-17513] remove deprecated endpoints calls from cypress steps
  cypress/e2e/EnrollmentAddEventPage/EnrollmentAddEventPageForm/index.js
  cypress/e2e/EnrollmentPage/BreakingTheGlass/index.js
  cypress/e2e/EnrollmentPage/HiddenProgramStage/index.js
  cypress/e2e/NewEventThroughAddRelationship/index.js
Labels: e2e-tests

#3635 fix: [DHIS2-17054] handle empty expression value
  packages/rules-engine/src/processors/rulesEffectsProcessor/rulesEffectsProcessor.js
  src/core_modules/capture-core/components/WidgetFeedback/WidgetFeedbackContent/WidgetFeedbackContent.js
  src/core_modules/capture-core/rules/__tests__/rulesEffectsForTrackerProgram.test.js
Labels: testing

#3610 fix: [DHIS2-16488] Allow programs with no TET write access
  i18n/en.pot
  src/core_modules/capture-core/components/NoWriteAccessMessage/NoWriteAccessMessage.component.js
  src/core_modules/capture-core/components/Pages/New/NewPage.component.js
  src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.container.js
  src/core_modules/capture-core/components/WidgetEnrollment/hooks/useProgram.js
  src/core_modules/capture-core/components/WidgetProfile/WidgetProfile.component.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/buildPrograms.js
Labels: testing

#3634 fix: [DHIS2-17115] Translatable plugin titles
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/enrollment/EnrollmentFactory.js
Labels: e2e-tests

#3642 feat: [DHIS2-16293][DHIS2-16294] Category combination in event program forms
  cypress/e2e/NewPage.feature
  cypress/e2e/NewPage/index.js
  cypress/e2e/ViewPage/EditEventPageForm.feature
  cypress/e2e/ViewPage/EditEventPageForm/index.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/DataEntry.component.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/getConvertedNewSingleEvent.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/saveNewSingleEventAddAnother.epics.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/helpers/getOpenDataEntryActions.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/NewEventDataEntryWrapper.component.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/SingleEventRegistrationEntry.container.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/SingleEventRegistrationEntry.types.js
  src/core_modules/capture-core/components/DataEntry/DataEntry.component.js
  src/core_modules/capture-core/components/Pages/New/NewPage.component.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.component.js
  src/core_modules/capture-core/components/Pages/New/TopBar.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/EventDetailsSection.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/EventDetailsSection.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/EventDetailsSection/eventDetails.actions.js
  src/core_modules/capture-core/components/Pages/ViewEvent/TopBar.container.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/Program/CategorySelector.component.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/Program/ProgramSelector.component.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/QuickSelector.component.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/QuickSelector.types.js
  src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.component.js
  src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.container.js
  src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.types.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/editEventDataEntry.actions.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.component.js
  src/core_modules/capture-core/flow/typeDeclarations.js
Labels: testing, e2e record

#3656 fix: [DHIS2-16919] navigation to tracker event without org unit id
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser.feature
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/index.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/ReduxProvider/TeiWorkingListsReduxProvider.container.js
Labels: testing

#3672 fix: [DHIS2-17536] remove delete relationship deprecated endpoint
  cypress/e2e/ViewPage/EditEventPageForm.feature
  cypress/e2e/ViewPage/EditEventPageForm/index.js
  src/core_modules/capture-core/components/Pages/ViewEvent/Relationship/ViewEventRelationships.actions.js
  src/core_modules/capture-core/components/Pages/ViewEvent/Relationship/ViewEventRelationships.epics.js
  src/core_modules/capture-core/components/Relationships/Relationships.component.js
Labels: testing

#3614 docs: fix section level
  docs/user/using-the-capture-app.md
Labels: skip-e2e-tests

#3636 chore: add plugin documentation
  docs/developer/configure-a-capture-plugin.mdx
  docs/developer/develop-a-capture-plugin.md
  docs/developer/enrollment-plugins/developer-details.md
  docs/developer/enrollment-plugins/introduction.md
  docs/developer/enrollment-plugins/manual-setup.mdx
  docs/developer/form-field-plugins/developer-details.md
  docs/developer/form-field-plugins/introduction.md
  docs/developer/form-field-plugins/manual-setup.md
  docs/developer/getting-started.md
  docs/developer/resources/capture-form-with-one-field.png
  docs/developer/resources/capture-form-with-plugin.png
  docs/developer/resources/capture-form-without-plugins.png
  docs/developer/resources/data-store-after-keys-are-created.png
  docs/developer/resources/data-store-management-app.png
  docs/developer/resources/data-store-management-data-entry-forms-empty.png
  docs/developer/resources/data-store-new-key.png
  docs/developer/resources/growth-charts-weight-for-age.png
  docs/developer/resources/mock-civil-registry-plugin.png
  docs/developer/resources/tpc-form-field-demo.png
  docs/developer/resources/tracker-plugin-configurator-logo.png
Labels: skip-e2e-tests

#3692 chore: fix broken link in plugin docs
  docs/developer/getting-started.md
Labels: skip-e2e-tests

#3683 fix: [DHIS2-17488] hide program stage if no data read access
  cypress/e2e/EnrollmentPage/StagesAndEventsWidget.feature
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.container.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.types.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/hooks/useProgramMetadata.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/hooks/useProgramStages.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stages.component.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/types/common.types.js
Labels: testing
