Repository dhis2/capture-app, pull requests merged in 2024-07, with the labels that each got.

#3657 feat: [DHIS2-17068] Check Related Stage Eligibility for Storing Events
  i18n/en.pot
  src/core_modules/capture-core/components/WidgetRelatedStages/RelatedStagesActions/RelatedStagesActions.component.js
  src/core_modules/capture-core/components/WidgetRelatedStages/hooks/useCanAddNewEventToStage.js
Labels: testing

#3693 chore: [DHIS2-17654] Restore and clean disabled Cypress tests
  cypress/e2e/AllAccessibleRecordsPage/AllAccessibleRecordsPage.feature
  cypress/e2e/AllAccessibleRecordsPage/AllAccessibleRecordsPage.js
  cypress/e2e/EnrollmentAddEventPage/EnrollmentAddEventPageForm/EnrollmentAddEventPageForm.feature
  cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageNavigation/EnrollmentEditEventPageNavigation.feature
  cypress/e2e/EnrollmentPage/BreakingTheGlass/BreakingTheGlass.feature
  cypress/e2e/EnrollmentPage/StagesAndEventsWidget/StagesAndEventsWidget.feature
  cypress/e2e/NewEventThroughAddRelationship/NewEventThroughAddRelationship.feature
  cypress/e2e/NewPage/NewPage.feature
  cypress/e2e/ScopeSelector/ScopeSelector.feature
  cypress/e2e/SearchPage/SearchPage.feature
  cypress/e2e/SearchThroughAddRelationship/SearchThroughAddRelationship.feature
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentAddEventPage/WidgetsForEnrollmentAddEventPage.feature
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard/WidgetsForEnrollmentDashboard.feature
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent/WidgetsForEnrollmentEditEvent.feature
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEventSchedule/WidgetsForEventSchedule.feature
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/TeiWorkingListsUser.feature
Labels: e2e-tests

#3685 fix: [DHIS2-17608] enroll a tracked entity from a single event relationship
  cypress/e2e/ViewPage/EditEventPageForm/EditEventPageForm.feature
  cypress/e2e/ViewPage/EditEventPageForm/EditEventPageForm.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/Enrollment/DataEntryEnrollment.component.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/Enrollment/DataEntryEnrollment.container.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/DataEntry/Enrollment/dataEntryEnrollment.types.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/RegisterTei/DataEntry/RegisterTeiDataEntry.actions.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/RegisterTei/RegistrationSection/registrationSection.actions.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/RegisterTei/registerTei.actions.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/TeiSearch/SearchProgramSelector/searchProgramSelector.actions.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/TeiSearch/actions/teiSearch.actions.js
  src/core_modules/capture-core/reducers/descriptions/newRelationship.reducerDescription.js
  src/core_modules/capture-core/reducers/descriptions/teiSearch.reducerDescription.js
  src/epics/trackerCapture.epics.js
Labels: testing

#3695 fix: [DHIS2-17422] Can Not Delete Program Stage Events
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.actions.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.epics.js
Labels: testing

#3673 fix: [DHIS2-17531] use new image endpoint in search tracked entity results
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/TeiSearch/epics/teiSearch.epics.js
  src/core_modules/capture-core/components/PossibleDuplicatesDialog/possibleDuplicatesDialog.epics.js
  src/core_modules/capture-core/components/SearchBox/SearchForm/SearchForm.epics.js
  src/core_modules/capture-core/components/TeiSearch/epics/teiSearch.epics.js
  src/core_modules/capture-core/trackedEntityInstances/getSubValues.js
  src/core_modules/capture-core/trackedEntityInstances/trackedEntityInstanceRequests.js
Labels: testing

#3698 fix: chrome crashes when opening applications-tab
  public/manifest.json
Labels: skip-e2e-tests

#3680 chore: bump ui-library version
  cypress/support/step_definitions/common/baseSteps.js
  i18n/ru.po
  package.json
  src/core_modules/capture-core/components/Pages/Enrollment/TopBar.container.js
  src/core_modules/capture-core/components/Pages/New/TopBar.container.js
  yarn.lock
Labels: e2e-tests, e2e record

#3696 fix: [DHIS2-16196] set MaxHeight to "more filters" in working lists
  src/core_modules/capture-core/components/ListView/Filters/FilterRestMenu/FilterRestMenu.component.js
Labels: testing

#3702 fix: [DHIS2-16852] confusing-ui-when-there-is-more-than-one-warning
  src/core_modules/capture-core/components/FormFields/New/HOC/messages/withDisplayMessages.js
Labels: testing

#3612 fix: [BETA-116][DHIS2-15896] validate values assigned from the rules engine
  src/core_modules/capture-core/components/D2Form/FormBuilder/FormBuilder.component.js
  src/core_modules/capture-core/reducers/descriptions/form.reducerDescription.js
Labels: testing

#3688 fix: [DHIS2-17398] improve unique ID search
  cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageForm/EnrollmentEditEventPageForm.feature
  i18n/en.pot
  src/core_modules/capture-core/components/DataEntries/Enrollment/EnrollmentDataEntry.component.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.component.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/RegisterTei.component.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/RegisterTei.container.js
  src/core_modules/capture-core/components/Pages/NewRelationship/RegisterTei/RegisterTei.types.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/TeiSearch/actions/teiSearch.actions.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/TeiSearch/epics/teiSearch.epics.js
  src/core_modules/capture-core/components/SearchBox/SearchForm/SearchForm.epics.js
  src/core_modules/capture-core/components/TeiSearch/actions/teiSearch.actions.js
  src/core_modules/capture-core/components/TeiSearch/epics/teiSearch.epics.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/DataEntry.container.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/FormFoundation/DataElement.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/enrollment/DataElementFactory.js
  src/epics/trackerCapture.epics.js
Labels: testing

#3655 fix: [DHIS2-8814] Table in custom form overflows container with no scrollbar
  src/core_modules/capture-core/components/D2Form/D2Section.component.js
Labels: testing

#3710 fix: [DHIS2-17736] Dropdown Regression in Registration Form
  src/core_modules/capture-core/components/D2Form/D2Section.component.js
Labels: testing

#3697 fix: [DHIS2-17653] Exclude Linked Events from Dropdown List in Actions Widget
  i18n/en.pot
  src/core_modules/capture-core/components/WidgetRelatedStages/RelatedStagesActions/RelatedStagesActions.component.js
  src/core_modules/capture-core/components/WidgetRelatedStages/hooks/useAvailableRelatedStageEvents.js
Labels: e2e-tests, testing

#3714 chore: [DHIS2-17730] flaky scenario in EnrollmentEditEventPageForm.feature
  cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageForm/EnrollmentEditEventPageForm.feature
  cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageForm/EnrollmentEditEventPageForm.js
Labels: e2e-tests

#3711 chore: [DHIS2-17733] flaky scenario in NewPage.feature
  cypress/e2e/NewPage/NewPage.js
Labels: e2e-tests

#3716 chore: [DHIS2-17657] flaky scenario in EnrollmentAddEventPageForm.feature
  cypress/e2e/EnrollmentAddEventPage/EnrollmentAddEventPageForm/EnrollmentAddEventPageForm.feature
  cypress/e2e/EnrollmentAddEventPage/EnrollmentAddEventPageForm/EnrollmentAddEventPageForm.js
Labels: e2e-tests

#3717 fix: [DHIS2-15687] display translated options in profile widget
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/helpers/convertClientToView.js
Labels: testing

#3699 feat: [DHIS2-17589] show absolute date when hovering over relative dates
  i18n/en.pot
  src/core_modules/capture-core/components/CardList/CardList.types.js
  src/core_modules/capture-core/components/CardList/CardListItem.component.js
  src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.component.js
  src/core_modules/capture-core/components/WidgetEnrollment/hooks/useEnrollment.js
  src/core_modules/capture-core/components/WidgetNote/NoteSection/NoteSection.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageOverview/StageOverview.component.js
Labels: e2e-tests, testing
