Repository dhis2/capture-app, pull requests merged in 2024-04, with the labels that each got.

#3597 fix: [DHIS2-16999] filter assign rule effects in the view event page
  src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/viewEventDataEntry.actions.js
  src/core_modules/capture-core/rules/filterApplicableRuleEffects.js
  src/core_modules/capture-core/rules/index.js
Labels: testing, RCB approved

#3584 fix: [DHIS2-17131] schedule dates with format DD-MM-YYYY
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/helpers/deriveAutoGenerateEvents.js
Labels: awaiting RCB approval, testing, RCB approved

#3593 fix: [DHIS2-17096] show/hide option groups in profile widget
  src/core_modules/capture-core/components/WidgetProfile/WidgetProfile.component.js
  src/core_modules/capture-core/components/WidgetProfile/hooks/useApiProgram.js
  src/core_modules/capture-core/components/WidgetProfile/hooks/useOptionGroups.js
  src/core_modules/capture-core/components/WidgetProfile/hooks/useProgram.js
Labels: awaiting RCB approval, testing, RCB approved

#3595 fix: [DHIS2-17177] Registration page stuck after failed save
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
  src/epics/trackerCapture.epics.js
Labels: awaiting RCB approval, testing, RCB approved

#3603 fix: [DHIS2-16931] Working list hides delete button
  src/core_modules/capture-core/components/ListView/withEndColumnMenu/RowMenu.component.js
Labels: awaiting RCB approval, testing, RCB approved

#3601 fix: [DHIS2-17161] Do not update attribute values from enrollment Widget
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/useCommonEnrollmentDomainData/useCommonEnrollmentDomainData.js
  src/core_modules/capture-core/components/WidgetEnrollment/hooks/useEnrollment.js
Labels: awaiting RCB approval, testing, RCB approved

#3602 chore: cypress login issue v42
  cypress/e2e/SmokeTests.feature
  cypress/support/commands.js
Labels: e2e-tests

#3618 fix: [DHIS2-17225] cannot add TET with polygon or coordiante
  cypress/e2e/NewPage.feature
  cypress/e2e/NewPage/index.js
  src/core_modules/capture-core/components/DataEntries/TrackedEntityInstance/TrackedEntityInstanceDataEntry.component.js
  src/core_modules/capture-ui/CoordinateField/CoordinateField.component.js
Labels: awaiting RCB approval, testing, RCB approved

#3621 fix: [BETA-102] handle Arabic dates when registering with auto-generate events
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/helpers/deriveAutoGenerateEvents.js
Labels: testing, RCB approved

#3615 fix: [DHIS2-17195] implement d2:condition
  packages/rules-engine/src/d2Functions/getD2Functions.js
  packages/rules-engine/src/d2Functions/getD2Functions.types.js
  packages/rules-engine/src/services/expressionService/executeExpression.js
  src/core_modules/capture-core/rules/__tests__/ruleEffectsForEventProgram.test.js
Labels: testing, RCB approved
