Repository dhis2/capture-app, pull requests merged in 2025-04, with the labels that each got.

#4028 fix: [DHIS2-19336] provide empty array instead of `null` to `RuleEnrollmentJs`
  src/core_modules/capture-core/rules/RuleEngine/helpers/InputBuilder.js
Labels: testing

#4044 fix: [DHIS2-19415] editing two fields simultaneously blocks saving
  src/core_modules/capture-core/components/DataEntries/Enrollment/epics/enrollment.epics.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/newEventDataEntry.epics.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/epics/dataEntryRules.epics.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/epics/editEventDataEntry.epics.js
Labels: preview, e2e-tests

#4042 refactor: enrollment quick actions and eslint improvements
  .eslintrc
  .github/workflows/verify-app.yml
  config/eslint/webpack.config.js
  docs/ts-migration.md
  package.json
  src/core_modules/capture-core/components/Buttons/SimpleSplitButton.component.tsx
  src/core_modules/capture-core/components/CardList/CardList.component.tsx
  src/core_modules/capture-core/components/CardList/CardListItem.component.tsx
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentQuickActions/EnrollmentQuickActions.component.tsx
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentQuickActions/EnrollmentQuickActions.types.ts
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentQuickActions/QuickActionButton/QuickActionButton.tsx
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentQuickActions/QuickActionButton/QuickActionButton.types.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentQuickActions/QuickActionButton/QuickActionButton.types.ts
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentQuickActions/index.ts
  src/core_modules/capture-core/components/Tooltips/ConditionalTooltip/ConditionalTooltip.component.js
  src/core_modules/capture-core/components/Tooltips/ConditionalTooltip/ConditionalTooltip.component.tsx
  src/core_modules/capture-core/components/Tooltips/ConditionalTooltip/index.ts
  src/core_modules/capture-core/metaData/DataElement/DataElement.ts
  src/core_modules/capture-core/metaData/DataElement/DateDataElement.ts
  src/core_modules/capture-core/metaData/FormFieldPluginConfig/FormFieldPluginConfig.tsx
  src/core_modules/capture-core/metaData/FormFieldPluginConfig/index.ts
  src/core_modules/capture-core/metaData/Icon/Icon.tsx
  src/core_modules/capture-core/metaData/Icon/index.ts
  src/core_modules/capture-core/metaData/OptionSet/Option.ts
  src/core_modules/capture-core/metaData/OptionSet/OptionSet.ts
  tsconfig.checkts.json
  tsconfig.json
  yarn.lock
Labels: skip-e2e-tests, e2e record

#4004 fix: [DHIS2-18952] Form name in widgets
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/useTEIRelationshipsWidgetMetadata.js
  src/core_modules/capture-core/components/WidgetsRelationship/common/RelationshipsWidget/useRelationshipTypes.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/common/factory/searchGroup/SearchGroupFactory.js
Labels: testing

#4014 feat: [DHIS2-16991] Add clear button
  src/core_modules/capture-core/components/D2Form/field/Components/DateField/DateFieldForForm.component.js
  src/core_modules/capture-core/components/D2Form/field/configs/dateTimeField/getDateTimeFieldConfig.js
  src/core_modules/capture-core/components/D2Form/field/configs/dateTimeRangeField/getDateTimeRangeFieldConfig.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/DataEntry.component.js
  src/core_modules/capture-core/components/FormFields/New/Fields/DateAndTimeFields/DateField/DateField.component.js
  src/core_modules/capture-core/components/WidgetEnrollment/MapModal/Coordinates/Coordinates.component.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/DataEntry.component.js
  src/core_modules/capture-ui/CoordinateField/CoordinateField.component.js
  src/core_modules/capture-ui/CoordinateField/coordinateField.module.css
  src/core_modules/capture-ui/DateAndTimeFields/DateField/Date.component.js
  src/core_modules/capture-ui/DateAndTimeFields/DateTimeField/DateTime.component.js
  src/core_modules/capture-ui/DateAndTimeFields/DateTimeField/dateTime.module.css
Labels: testing
