Repository dhis2/capture-app, pull requests merged in 2025-01, with the labels that each got.

#3933 chore: [DHIS2-18736] fix Cypress tests broken due to the change of year
  cypress/e2e/EnrollmentPage/StagesAndEventsWidget/StagesAndEventsWidget.feature
  cypress/e2e/EnrollmentPage/StagesAndEventsWidget/StagesAndEventsWidget.js
  cypress/e2e/WidgetsForEnrollmentPages/WidgetEnrollment/index.js
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentAddEventPage/WidgetsForEnrollmentAddEventPage.feature
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard/WidgetsForEnrollmentDashboard.feature
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent/WidgetsForEnrollmentEditEvent.feature
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiBulkActions/TeiBulkActions.feature
Labels: e2e-tests

#3927 fix: [DHIS2-18569] Relationship widget limited to 50 entries
  src/core_modules/capture-core-utils/featuresSupport/support.js
  src/core_modules/capture-core/components/WidgetsRelationship/common/useRelationships/useRelationships.js
Labels: testing

#3908 fix: [DHIS2-17613] Use new note endpoint
  src/core_modules/capture-core-utils/featuresSupport/support.js
  src/core_modules/capture-core/components/Pages/ViewEvent/Notes/viewEventNotes.actions.js
  src/core_modules/capture-core/components/Pages/ViewEvent/Notes/viewEventNotes.epics.js
  src/core_modules/capture-core/components/WidgetEnrollmentNote/WidgetEnrollmentNote.actions.js
  src/core_modules/capture-core/components/WidgetEnrollmentNote/WidgetEnrollmentNote.epics.js
  src/core_modules/capture-core/components/WidgetEventNote/WidgetEventNote.actions.js
  src/core_modules/capture-core/components/WidgetEventNote/WidgetEventNote.epics.js
Labels: testing

#3935 fix: [DHIS2-18355] runtime error occurs when saving empty widget in Related stages
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/Validated.container.js
Labels: testing

#3938 fix: [DHIS2-18836] show 'Profile' instead of 'False' during loading
  src/core_modules/capture-core/components/WidgetProfile/WidgetProfile.component.js
  src/core_modules/capture-core/components/WidgetProfile/hooks/useTrackedEntityInstances.js
Labels: testing

#3915 chore: [DHIS2-18464] align validators result structure
  i18n/en.pot
  src/core_modules/capture-core/components/DataEntries/Enrollment/EnrollmentWithFirstStageDataEntry/fieldValidators/eventDate.validatorContainersGetter.js
  src/core_modules/capture-core/components/DataEntries/Enrollment/fieldValidators/categoryOptions.validatorContainersGetter.js
  src/core_modules/capture-core/components/DataEntries/Enrollment/fieldValidators/enrollmentDate.validatorContainersGetter.js
  src/core_modules/capture-core/components/DataEntries/Enrollment/fieldValidators/incidentDate.validatorContainerGetter.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/fieldValidators/eventDate.validatorContainersGetter.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/fieldValidators/note.validatorContainersGetter.js
  src/core_modules/capture-core/components/DataEntry/dataEntryField/internal/dataEntryField.utils.js
  src/core_modules/capture-core/components/DataEntryDhis2Helpers/AOC/categoryOptions.validatorContainersGetter.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/fieldValidators/categoryOptions.validatorContainersGetter.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/fieldValidators/eventDate.validatorContainersGetter.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/fieldValidators/note.validatorContainersGetter.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/fieldValidators/categoryOptions.validatorContainersGetter.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/fieldValidators/eventDate.validatorContainersGetter.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/fieldValidators/index.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/fieldValidators/note.validatorContainersGetter.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/fieldValidators/orgUnit.validatorContainersGetter.js
Labels: testing

#3941 fix: [DHIS2-18668] remove delete button in enrollment event pages
  cypress/e2e/NewPage/NewPage.js
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentAddEventPage/WidgetsForEnrollmentAddEventPage.feature
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent/WidgetsForEnrollmentEditEvent.feature
  src/core_modules/capture-core/components/WidgetProfile/OverflowMenu/OverflowMenu.component.js
  src/core_modules/capture-core/components/WidgetProfile/OverflowMenu/OverflowMenu.container.js
  src/core_modules/capture-core/components/WidgetProfile/OverflowMenu/OverflowMenu.types.js
  src/core_modules/capture-core/components/WidgetProfile/WidgetProfile.component.js
Labels: testing, e2e record

#3879 feat: [DHIS2-18325] Show orgunit selector in the new event form
  cypress/e2e/ScopeSelector/ScopeSelector.feature
  cypress/e2e/ScopeSelector/ScopeSelector.js
  i18n/en.pot
  packages/rules-engine/src/d2Functions/getD2Functions.types.js
  packages/rules-engine/src/rulesEngine.types.js
  packages/rules-engine/src/services/VariableService/VariableService.js
  packages/rules-engine/src/services/VariableService/variableService.types.js
  src/core_modules/capture-core/components/DataEntries/Enrollment/EnrollmentDataEntry.component.js
  src/core_modules/capture-core/components/DataEntries/Enrollment/EnrollmentWithFirstStageDataEntry/EnrollmentWithFirstStageDataEntry.component.js
  src/core_modules/capture-core/components/DataEntries/Enrollment/EnrollmentWithFirstStageDataEntry/EnrollmentWithFirstStageDataEntry.container.js
  src/core_modules/capture-core/components/DataEntries/Enrollment/EnrollmentWithFirstStageDataEntry/EnrollmentWithFirstStageDataEntry.types.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/DataEntry.component.js
  src/core_modules/capture-core/components/DataEntry/index.js
  src/core_modules/capture-core/components/FormFields/New/HOC/withCenterPoint.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/TopBar/TopBar.component.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/OrgUnitSelector.component.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/QuickSelector.component.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/QuickSelector.types.js
  src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.component.js
  src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.container.js
  src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.types.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/DataEntry.component.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/DataEntry.container.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/dataEntry.types.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/epics/dataEntryRules.epics.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/fieldValidators/index.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/fieldValidators/orgUnit.validatorContainersGetter.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/helpers/getOpenDataEntryActions.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/helpers/getRulesActions.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/OrgUnitFetcher/OrgUnitFetcher.component.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/SavingText/SavingText.component.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/SavingText/savingText.types.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/Validated.component.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/Validated.container.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/getConvertedAddEvent.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/useBuildNewEventPayload.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/useLifecycle.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/validated.types.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/ScheduleText/ScheduleText.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.container.js
  src/core_modules/capture-core/metadataRetrieval/coreOrgUnit/getCoreOrgUnitFn.js
  src/core_modules/capture-core/metadataRetrieval/coreOrgUnit/index.js
  src/core_modules/capture-core/rules/rules.types.js
  src/core_modules/capture-core/utils/portal/index.js
  src/core_modules/capture-core/utils/portal/usePlacementDomNode.js
  src/core_modules/capture-ui/CoordinateField/CoordinateField.component.js
Labels: testing

#3939 test: [DHIS2-17853] Related stages Cypress tests
  cypress/e2e/RelatedStages/RelatedStages.feature
  cypress/e2e/RelatedStages/RelatedStages.js
  src/core_modules/capture-core/components/FormFields/New/Fields/OrgUnitField/OrgUnitField.component.js
  src/core_modules/capture-core/components/WidgetRelatedStages/FormComponents/OrgUnitSelectorForRelatedStages.js
  src/core_modules/capture-core/components/WidgetRelatedStages/LinkToExisting/LinkToExisting.component.js
  src/core_modules/capture-core/components/WidgetRelatedStages/RelatedStagesActions/RelatedStagesActions.component.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/EventRow/DeleteActionButton/DeleteActionButton.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/OverflowMenu/Modal/UnlinkModal.js
Labels: e2e-tests

#3943 fix: [DHIS2-18673] prevent saving in profile widget when validation errors are present
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/dataEntry.actions.js
Labels: testing

#3950 fix: [DHIS2-18902] keep program selection on unique id fallback search
  src/core_modules/capture-core/components/SearchBox/SearchBox.actions.js
  src/core_modules/capture-core/components/SearchBox/SearchForm/SearchForm.epics.js
Labels: testing

#3925 feat: [DHIS2-18329] Add org unit selector in schedule event form
  i18n/en.pot
  src/core_modules/capture-core/components/Widget/widgetCollapsible.types.js
  src/core_modules/capture-core/components/Widget/widgetNonCollapsible.types.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/DataEntry/dataEntryFieldLabels.module.css
  src/core_modules/capture-core/components/WidgetEventSchedule/InfoBox/InfoBox.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/ScheduleDate/ScheduleDate.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/ScheduleDate/dataEntryFieldLabels.module.css
  src/core_modules/capture-core/components/WidgetEventSchedule/ScheduleDate/scheduleDate.types.js
  src/core_modules/capture-core/components/WidgetEventSchedule/ScheduleOrgUnit/ScheduleOrgUnit.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/ScheduleOrgUnit/commonProps.js
  src/core_modules/capture-core/components/WidgetEventSchedule/ScheduleOrgUnit/dataEntryFieldLabels.module.css
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.container.js
  src/core_modules/capture-core/components/WidgetEventSchedule/widgetEventSchedule.types.js
Labels: testing

#3928 fix: [DHIS2-18582] Data element with number option set are not displayed in Stages and Events widget
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/StageDetail.component.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/hooks/helpers.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/hooks/useClientDataElements.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/hooks/useEventList.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/types/common.types.js
Labels: testing
