Repository dhis2/capture-app, pull requests merged in 2025-03, with the labels that each got.

#3982 feat: [DHIS2-18944] add effect to refresh list on event deletion
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ViewMenuSetup/EventWorkingListsViewMenuSetup.component.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ViewMenuSetup/EventWorkingListsViewMenuSetup.types.js
Labels: testing

#3988 fix: update github actions cache v2 -> v4
  .github/workflows/preview.yml
  .github/workflows/verify-app.yml
Labels: e2e-tests

#3980 chore: [DHIS2-18391] show error message for invalid schedule date, enrollment date and incident date
  src/core_modules/capture-core/components/WidgetEnrollment/Date/Date.component.js
  src/core_modules/capture-core/components/WidgetEnrollment/WidgetEnrollment.component.js
  src/core_modules/capture-core/components/WidgetEnrollment/hooks/useProgram.js
  src/core_modules/capture-core/components/WidgetEventSchedule/ScheduleButtons/ScheduleButtons.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/ScheduleButtons/scheduleButtons.types.js
  src/core_modules/capture-core/components/WidgetEventSchedule/ScheduleDate/ScheduleDate.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/ScheduleDate/scheduleDate.types.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.component.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.container.js
  src/core_modules/capture-core/components/WidgetEventSchedule/widgetEventSchedule.types.js
  src/core_modules/capture-ui/DateAndTimeFields/DateField/Date.component.js
Labels: testing

#3991 fix: [DHIS2-19140] Changelog modal unmounts when loading
  cypress/e2e/WidgetsForEnrollmentPages/WidgetChangelog/index.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/Changelog/Changelog.component.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/Changelog/Changelog.container.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/Changelog/Changelog.types.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/hooks/useListDataValues.js
Labels: testing

#3997 fix: [DHIS2-18763] Org. unit context selector does not work for View event in Event programs
  cypress/e2e/ScopeSelector/ScopeSelector.feature
  cypress/e2e/ScopeSelector/ScopeSelector.js
  src/core_modules/capture-core/components/Pages/ViewEvent/TopBar.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/ViewEvent.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/ViewEvent.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/viewEvent.actions.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventPage.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/epics/viewEvent.epics.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ReduxProvider/EventWorkingListsReduxProvider.container.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/eventWorkingLists.actions.js
Labels: testing

#3998 chore: [DHIS2-19196][LIBS-726] bump @dhis2-ui/calendar from 10.0.3 to 10.4.0
  package.json
  yarn.lock
Labels: testing

#3974 feat: [DHIS2-16338] Display event's org. unit in working lists
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/TeiWorkingListsUser.js
  i18n/en.pot
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/TemplateSetup/EventWorkingListsTemplateSetup.component.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/getTemplates.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/helpers/eventFilters/apiEventFilterToClientConfigConverter/convertToClientConfig.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/helpers/eventFilters/clientConfigToApiEventFilterQueryCriteriaConverter/convertToEventFilterEventQueryCriteria.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingListsCommon/useDefaultColumnConfiguration/useDefaultColumnConfig.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/hooks/useDefaultColumnConfig.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/hooks/useInjectDataFetchingMeta.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/TEIFilters/apiTEIFilterToClientConfigConverter/convertSortToClient.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/TEIFilters/apiTEIFilterToClientConfigConverter/getCustomColumnsConfiguration.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/eventFilters/additionalFiltersConvertor.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/helpers/templates/buildArgumentsForTemplate.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/types/concept.types.js
  src/core_modules/capture-core/events/mainPropertyNames.const.js
Labels: e2e-tests, testing

#3995 fix: [DHIS2-19165] handle empty schedule date
  src/core_modules/capture-core-utils/featuresSupport/support.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/helpers/deriveFirstStageDuringRegistrationEvent.js
  src/core_modules/capture-core/components/DataEntries/converters/getConvertedRelatedStageEvent/getConvertedRelatedStageEvent.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/getConvertedAddEvent.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/editEventDataEntry.actions.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.component.js
Labels: testing

#4002 fix: [DHIS2-19221] enrollment dashboard workflows
  i18n/en.pot
  package.json
  src/components/AppLoader/init.js
  src/core_modules/capture-core-utils/featuresSupport/support.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.actions.js
  src/core_modules/capture-core/components/Pages/Enrollment/MissingMessage.component.js
  src/core_modules/capture-core/components/Pages/Enrollment/epics/enrollmentPage.epics.js
  src/core_modules/capture-core/components/Pages/Enrollment/epics/fetchEnrollment.epics.js
  src/core_modules/capture-core/components/Pages/Enrollment/epics/index.js
  src/core_modules/capture-core/components/Pages/New/NewPage.container.js
  src/core_modules/capture-core/components/Pages/New/hooks/index.js
  src/core_modules/capture-core/components/Pages/New/hooks/useTrackedEntityAttributes.js
  src/core_modules/capture-core/components/Pages/New/hooks/useTrackedEntityInstances.js
  src/core_modules/capture-core/metaData/SystemSettings/SystemSettings.js
  src/core_modules/capture-core/metaDataStoreLoaders/programs/quickStoreOperations/storePrograms.js
  src/core_modules/capture-core/metaDataStoreLoaders/systemSettings/cacheSystemSetttings.js
  src/core_modules/capture-core/metadataRetrieval/orgUnitName/index.js
  src/core_modules/capture-core/metadataRetrieval/orgUnitName/orgUnitName.js
  src/core_modules/capture-core/reducers/descriptions/breakTheGlass.reducerDescription.js
  src/core_modules/capture-core/reducers/descriptions/enrollmentPage.reducerDescription.js
  src/core_modules/capture-core/storageControllers/storageControllers.js
  src/core_modules/capture-core/storageControllers/userStorageController.js
  src/epics/trackerCapture.epics.js
  src/reducers/descriptions/trackerCapture.reducerDescriptions.js
Labels: testing

#4003 fix: [DHIS2-16918] Event relationship URL link is broken
  src/core_modules/capture-core/components/Pages/ViewEvent/RightColumn/RelationshipsSection/ConnectedEntity/TrackedEntityInstance.js
Labels: testing

#4024 chore: [DHIS2] allow incremental typescript refactor
  .babelrc
  .eslintrc
  .flowconfig
  .github/workflows/verify-app.yml
  TYPESCRIPT_MIGRATION.md
  flow-typed/@js-temporal-polyfill.js.flow
  flow-typed/typescript.js.flow
  package.json
  src/components/AppStart/AppStart.component.tsx
  src/components/AppStart/CacheExpired.component.tsx
  src/components/AppStart/JSSProviderShell.component.tsx
  src/components/AppStart/index.ts
  src/declarations.d.ts
  tsconfig.checkts.json
  tsconfig.json
  yarn.lock
Labels: preview, skip-e2e-tests
