Repository dhis2/capture-app, pull requests merged in 2025-05, with the labels that each got.

#4015 feat: [DHIS2-18382] Replace TE org.unit with the owner org. unit in workingList
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/TeiWorkingListsUser.js
  i18n/en.pot
  src/core_modules/capture-core/components/List/OnlineList/OnlineList.component.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/ReduxProvider/TeiWorkingListsReduxProvider.container.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/hooks/useDefaultColumnConfig.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getEventListData/convertToClientEvents.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getEventListData/getEventListData.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getListDataCommon/getSubvalues.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/convertToClientTeis.js
Labels: testing

#4013 feat: [DHIS2-19190] Read Only for OrgUnit Selector
  cypress/e2e/ScopeSelector/ScopeSelector.feature
  cypress/e2e/ScopeSelector/ScopeSelector.js
  i18n/en.pot
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/helpers/deriveAutoGenerateEvents.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/useBuildEnrollmentPayload.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/TopBar/TopBar.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/TopBar.container.js
  src/core_modules/capture-core/components/Pages/New/NewPage.container.js
  src/core_modules/capture-core/components/Pages/New/TopBar.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/TopBar.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventPage.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventPage.container.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/OrgUnitSelector.component.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/QuickSelector.component.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/QuickSelector.types.js
  src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.component.js
  src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.container.js
  src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.types.js
Labels: testing

#4045 fix: [DHIS2-19011] Forms retain values after search
  src/core_modules/capture-core/components/DataEntries/Enrollment/actions/open.actionBatchs.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/useLifecycle.js
  src/core_modules/capture-core/components/DataEntries/TeiRegistrationEntry/hooks/useFormValuesFromSearchTerms.js
  src/core_modules/capture-core/components/DataEntries/TrackedEntityInstance/actions/open.actionBatches.js
  src/core_modules/capture-core/components/Pages/New/NewPage.actions.js
  src/core_modules/capture-core/components/SearchBox/SearchBox.actions.js
  src/core_modules/capture-core/components/SearchBox/SearchBox.component.js
  src/core_modules/capture-core/components/SearchBox/SearchBox.container.js
  src/core_modules/capture-core/components/SearchBox/SearchForm/SearchForm.component.js
  src/core_modules/capture-core/components/SearchBox/SearchForm/SearchForm.types.js
  src/core_modules/capture-core/components/SearchBox/SearchResults/SearchResults.component.js
  src/core_modules/capture-core/components/SearchBox/SearchResults/SearchResults.container.js
  src/core_modules/capture-core/components/SearchBox/SearchResults/SearchResults.types.js
  src/core_modules/capture-core/components/SearchBox/SearchStatus/SearchStatus.component.js
  src/core_modules/capture-core/components/SearchBox/SearchStatus/SearchStatus.container.js
  src/core_modules/capture-core/components/SearchBox/SearchStatus/SearchStatus.types.js
  src/core_modules/capture-core/components/SearchBox/hooks/index.js
  src/core_modules/capture-core/components/SearchBox/hooks/useFallbackTriggered.js
  src/core_modules/capture-core/reducers/descriptions/newPage.reducerDescription.js
Labels: testing

#4031 chore: [DHIS2-18642] Cypress tests changelog
  cypress/e2e/WidgetsForEnrollmentPages/WidgetChangelog/Changelog.feature
  cypress/e2e/WidgetsForEnrollmentPages/WidgetChangelog/Changelog.js
  cypress/e2e/WidgetsForEnrollmentPages/WidgetChangelog/index.js
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent/WidgetsForEnrollmentEditEvent.feature
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentEditEvent/WidgetsForEnrollmentEditEvent.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogFilterBar/DropdownFilter.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogTable/ChangelogTableHeader.js
Labels: testing, e2e record

#4058 fix: [DHIS2-19441][DHIS2-19442] Missing translation
  i18n/en.pot
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/DataEntry.component.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/FormFoundation/DataElement.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/FormFoundation/types.js
  src/core_modules/capture-core/components/WidgetProfile/hooks/useApiProgram.js
Labels: testing

#4068 fix: [DHIS2-13236] Incorrect text on top of Profile widget
  cypress/e2e/WidgetsForEnrollmentPages/WidgetProfile/index.js
  i18n/en.pot
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/DataEntry.component.js
Labels: testing

#4067 fix: [DHIS2-19172] Auto-generated events do not have report date prefilled in new event form
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/helpers/deriveAutoGenerateEvents.js
  src/core_modules/capture-core/metaData/Program/ProgramStage.js
Labels: testing

#4060 feat: [DHIS2-10134] Disable fallback search button when TET have no searchable attributes
  i18n/en.pot
  src/core_modules/capture-core/components/SearchBox/SearchResults/SearchResults.component.js
Labels: testing

#4059 fix: [DHIS2-18671] Discard changes dialog not responding
  src/core_modules/capture-core/components/Pages/New/NewPage.component.js
  src/core_modules/capture-core/components/Pages/New/NewPage.container.js
  src/core_modules/capture-core/components/Pages/New/NewPage.types.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.container.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.types.js
  src/core_modules/capture-core/components/Pages/New/TopBar.container.js
  src/core_modules/capture-core/components/TopBarActions/TopBarActions.container.js
  src/core_modules/capture-core/components/TopBarActions/TopBarActions.types.js
Labels: testing

#4076 fix: [DHIS2-18839] TEA with number option set value does not show in Profile widget on Capture App
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/helpers/convertClientToView.js
Labels: testing

#4063 fix: [DHIS2-19530] deprecated api query params
  cypress/e2e/WidgetsForEnrollmentPages/WidgetEnrollment/index.js
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsDev/TeiWorkingListsDev.js
  src/core_modules/capture-core-utils/featuresSupport/support.js
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/Transfer/hooks/useUpdateOwnership.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/hooks/useFiltersOnly.js
Labels: testing

#4061 fix: [DHIS2-19467] form inconsistencies
  src/core_modules/capture-core/components/D2Form/D2Section.component.js
  src/core_modules/capture-core/components/D2Form/D2Section.container.js
  src/core_modules/capture-core/components/Pages/New/NewPage.actions.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.container.js
  src/core_modules/capture-core/reducers/descriptions/dataEntry.reducerDescription.js
  src/core_modules/capture-core/reducers/descriptions/form.reducerDescription.js
Labels: testing

#4087 chore: bump rule engine version 3.3.9 -> 3.3.10
  package.json
  src/core_modules/capture-core/rules/__tests__/ruleEffectsForEventProgram.test.js
  yarn.lock
Labels: e2e-tests

#4101 chore: remove unused deps
  package.json
  src/components/App/App.component.js
  src/setupTests.js
  yarn.lock
Labels: e2e-tests

#4043 fix: [DHIS2-18951] Ignore Non-searchable attributes error when validating unique attribute
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/enrollment/DataElementFactory.js
Labels: testing

#4105 chore: stabilize cypress flaky tests
  cypress/e2e/EnrollmentPage/HiddenProgramStage/HiddenProgramStage.js
  cypress/e2e/EnrollmentPage/StagesAndEventsWidget/StagesAndEventsWidget.js
  cypress/e2e/WidgetsForEnrollmentPages/WidgetProfile/index.js
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiBulkActions/TeiBulkActions.feature
  src/core_modules/capture-core/components/WidgetRelatedStages/RelatedStagesActions/RelatedStagesActions.container.js
  src/core_modules/capture-core/components/WidgetRelatedStages/hooks/useRelatedStageEvents.js
Labels: e2e-tests

#4064 test: [DHIS2-19509] add Cypress scenarios for BulkDataEntry
  cypress/e2e/MainPage/MainPage.feature
  cypress/e2e/MainPage/MainPage.js
  cypress/e2e/SearchPage/SearchPage.feature
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiBulkActions/TeiBulkActions.feature
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiBulkActions/TeiBulkActions.js
  cypress/support/commands.js
  cypress/support/step_definitions/common/baseSteps.js
  cypress/support/step_definitions/common/bulkDataEntry.js
  cypress/support/step_definitions/common/index.js
  src/core_modules/capture-core/components/Breadcrumbs/BulkDataEntryBreadcrumb/BulkDataEntryBreadcrumb.js
  src/core_modules/capture-core/components/List/OnlineList/OnlineList.component.js
  src/core_modules/capture-core/components/WidgetBulkDataEntry/BulkDataEntryActive/BulkDataEntryActive.component.js
  src/core_modules/capture-core/components/WidgetBulkDataEntry/BulkDataEntryIdle/BulkDataEntryIdle.component.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/BulkActionBar/Actions/BulkDataEntryAction/BulkDataEntryActionDropdownButton.component.js
Labels: e2e-tests
