Repository dhis2/capture-app, pull requests merged in 2025-02, with the labels that each got.

#3926 fix: [DHIS2-15685][DHIS2-18326] View an event without selecting org unit in Tracker Programs
  src/core_modules/capture-core/components/ScopeSelector/ScopeSelector.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
Labels: testing

#3947 chore: [DHIS2-18737] Scroll to top when navigating in the app
  src/components/AppLoader/AppLoader.component.js
  src/core_modules/capture-core/actions/navigateToEnrollmentOverview/navigateToEnrollmentOverview.epics.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/cancelNewSingleEvent.epics.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/saveNewSingleEvent.epics.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/saveNewSingleEventStage.epics.js
  src/core_modules/capture-core/components/MetadataAutoSelectInitializer/hooks/useMetadataAutoSelect.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.component.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPage.epics.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentPageDefault.container.js
  src/core_modules/capture-core/components/Pages/Enrollment/EnrollmentPageDefault/EnrollmentQuickActions/EnrollmentQuickActions.component.js
  src/core_modules/capture-core/components/Pages/Enrollment/MissingMessage.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPage.epics.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/ProgramStageSelector/ProgramStageSelector.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
  src/core_modules/capture-core/components/Pages/MainPage/MainPage.container.js
  src/core_modules/capture-core/components/Pages/New/NewPage.container.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.component.js
  src/core_modules/capture-core/components/Pages/New/RegistrationDataEntry/RegistrationDataEntry.epics.js
  src/core_modules/capture-core/components/Pages/Search/SearchPage.epics.js
  src/core_modules/capture-core/components/Pages/ViewEvent/epics/viewEvent.epics.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentPlugin/EnrollmentPlugin.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/useLinkedRecordClick.js
  src/core_modules/capture-core/components/ScopeSelector/QuickSelector/Program/EmptyPrograms.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useReset.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetEnrollmentId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetEventId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetOrgUnitId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetProgramId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetStageId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetTeiId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useResetViewEventId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useSetEnrollmentId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useSetOrgUnitId.js
  src/core_modules/capture-core/components/ScopeSelector/hooks/useSetProgramId.js
  src/core_modules/capture-core/components/SearchBox/SearchBox.epics.js
  src/core_modules/capture-core/components/SearchBox/SearchForm/SearchForm.epics.js
  src/core_modules/capture-core/components/TemplateSelector/TemplateSelector.container.js
  src/core_modules/capture-core/components/TopBarActions/TopBarActions.container.js
  src/core_modules/capture-core/components/TrackedEntityTypeSelector/TrackedEntityTypeSelector.epics.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.epics.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/OverflowMenu/OverflowMenu.component.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/ReduxProvider/TeiWorkingListsReduxProvider.container.js
  src/core_modules/capture-core/flow/typeDeclarations.js
  src/core_modules/capture-core/utils/routing/index.js
  src/core_modules/capture-core/utils/routing/useNavigate.js
  src/store/getStore.js
Labels: testing

#3940 feat: [DHIS2-8087] Add empty launch page
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/MainPage/MainPage.component.js
  src/core_modules/capture-core/components/Pages/MainPage/NoSelectionsInfoBox/NoSelectionsInfoBox.js
  src/core_modules/capture-core/components/Pages/MainPage/NoSelectionsInfoBox/index.js
Labels: testing

#3948 fix: [DHIS2-16871] Change Separator for Versions
  src/core_modules/capture-core-utils/featuresSupport/support.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/getConvertedNewSingleEvent.js
  src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/viewEventDataEntry.actions.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/getEventListData.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getEventListData/getEventListData.js
  src/core_modules/capture-core/converters/clientToServer.js
  src/core_modules/capture-core/events/convertEventAttributeOptions.js
Labels: testing

#3957 fix: [DHIS2-18978] Back buttons duplicate breadcrumbs
  cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageNavigation/EnrollmentEditEventPageNavigation.feature
  cypress/e2e/EnrollmentEditEventPage/EnrollmentEditEventPageNavigation/EnrollmentEditEventPageNavigation.js
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentAddEventPage/WidgetsForEnrollmentAddEventPage.js
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard/WidgetsForEnrollmentDashboard.feature
  cypress/e2e/WidgetsForEnrollmentPages/WidgetsForEnrollmentDashboard/WidgetsForEnrollmentDashboard.js
  i18n/en.pot
  src/core_modules/capture-core/components/Breadcrumbs/EnrollmentBreadcrumb/EnrollmentBreadcrumb.js
  src/core_modules/capture-core/components/Breadcrumbs/EventBreadcrumb/EventBreadcrumb.js
  src/core_modules/capture-core/components/Breadcrumbs/common/BreadcrumbItem.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.types.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/ViewEvent.component.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/LayoutComponentConfig/LayoutComponentConfig.js
  src/core_modules/capture-core/components/Pages/common/WidgetEventEditWrapper/WidgetEventEditWrapper.js
  src/core_modules/capture-core/components/WidgetEventEdit/widgetEventEdit.types.js
Labels: testing

#3916 feat: [DHIS2-18018][DHIS2-17853] show related stages widget in view event page
  cypress/e2e/RelatedStages/RelatedStages.feature
  cypress/e2e/RelatedStages/RelatedStages.js
  i18n/en.pot
  src/core_modules/capture-core/components/DataEntries/Enrollment/EnrollmentWithFirstStageDataEntry/EnrollmentWithFirstStageDataEntry.container.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/EnrollmentRegistrationEntry.types.js
  src/core_modules/capture-core/components/DataEntries/converters/getConvertedRelatedStageEvent/getConvertedRelatedStageEvent.js
  src/core_modules/capture-core/components/DataEntries/converters/getConvertedRelatedStageEvent/getConvertedRelatedStageEvent.types.js
  src/core_modules/capture-core/components/FormFields/New/Fields/OrgUnitField/OrgUnitField.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.component.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.container.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/EnrollmentEditEventPage.types.js
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/PageLayout/DefaultPageLayout.constants.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/DefaultEnrollmentLayout.types.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/EnrollmentPageLayout/LayoutComponentConfig/LayoutComponentConfig.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/enrollment.actions.js
  src/core_modules/capture-core/components/Pages/common/EnrollmentOverviewDomain/index.js
  src/core_modules/capture-core/components/WidgetEnrollment/enrollment.types.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/Validated.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/WidgetEventEdit.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/widgetEventEdit.types.js
  src/core_modules/capture-core/components/WidgetRelatedStages/FormComponents/OrgUnitSelectorForRelatedStages.js
  src/core_modules/capture-core/components/WidgetRelatedStages/LinkToExisting/LinkToExisting.component.js
  src/core_modules/capture-core/components/WidgetRelatedStages/RelatedStagesActions/RelatedStagesActions.component.js
  src/core_modules/capture-core/components/WidgetRelatedStages/RelatedStagesActions/RelatedStagesActions.container.js
  src/core_modules/capture-core/components/WidgetRelatedStages/RelatedStagesActions/RelatedStagesActions.types.js
  src/core_modules/capture-core/components/WidgetRelatedStages/RelatedStagesActions/index.js
  src/core_modules/capture-core/components/WidgetRelatedStages/WidgetRelatedStages.container.js
  src/core_modules/capture-core/components/WidgetRelatedStages/WidgetRelatedStages.types.js
  src/core_modules/capture-core/components/WidgetRelatedStages/hooks/index.js
  src/core_modules/capture-core/components/WidgetRelatedStages/hooks/useAddEventWithRelationship.js
  src/core_modules/capture-core/components/WidgetRelatedStages/hooks/useBuildRelatedStageEventPayload.js
  src/core_modules/capture-core/components/WidgetRelatedStages/hooks/useRelatedStages.js
  src/core_modules/capture-core/components/WidgetRelatedStages/index.js
  src/core_modules/capture-core/components/WidgetStagesAndEvents/Stages/Stage/StageDetail/EventRow/DeleteActionButton/DeleteActionButton.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/OverflowMenu/Modal/UnlinkAndDeleteModal.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/OverflowMenu/Modal/UnlinkAndDeleteModal.types.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/OverflowMenu/Modal/UnlinkModal.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/OverflowMenu/Modal/UnlinkModal.types.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/OverflowMenu/OverflowMenu.component.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/OverflowMenu/OverflowMenu.types.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/WidgetHeader/WidgetHeader.container.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/WidgetHeader/WidgetHeader.types.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/WidgetTwoEventWorkspace.container.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/WidgetTwoEventWorkspace.types.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/hooks/index.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/hooks/useLinkedEventByOriginId.js
  src/core_modules/capture-core/components/WidgetTwoEventWorkspace/index.js
  src/core_modules/capture-core/reducers/descriptions/enrollmentDomain.reducerDescription.js
Labels: testing

#3934 feat: [DHIS2-16782] Changelog sorting and filtering by user and data item
  i18n/en.pot
  src/core_modules/capture-core-utils/featuresSupport/support.js
  src/core_modules/capture-core/components/WidgetEventEdit/EventChangelogWrapper/EventChangelogWrapper.component.js
  src/core_modules/capture-core/components/WidgetProfile/OverflowMenu/TrackedEntityChangelogWrapper/TrackedEntityChangelogWrapper.component.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/Changelog/Changelog.component.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/Changelog/Changelog.constants.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/Changelog/Changelog.container.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/Changelog/Changelog.types.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/Changelog/index.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogFilterBar/ChangelogFilter.types.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogFilterBar/ChangelogFilterBar.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogFilterBar/DropdownFilter.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogFilterBar/index.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogTable/ChangelogTableHeader.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/ChangelogTable/ChangelogTableRow.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/hooks/useChangelogData.js
  src/core_modules/capture-core/components/WidgetsChangelog/common/hooks/useListDataValues.js
Labels: testing

#3958 docs: [DHIS2-18732] changelog docs
  docs/user/resources/images/changelog.png
  docs/user/resources/images/enable-tracked-entity-instance-audit-log.png
  docs/user/resources/images/open-event-changelog.png
  docs/user/resources/images/open-tracked-entity-changelog.png
  docs/user/using-the-capture-app.md
Labels: testing

#3965 fix: [DHIS2-18958] Add loading functionality to Search in all programs button
  src/core_modules/capture-core/components/SearchBox/SearchResults/SearchResults.component.js
Labels: testing

#3966 fix: [DHIS2-18704] registration form missing values
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/getSubValueForTei.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/useFormValues.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/useLifecycle.js
  src/core_modules/capture-core/components/Pages/New/NewPage.container.js
  src/core_modules/capture-core/components/Pages/New/hooks/useTrackedEntityInstances.js
Labels: testing

#3936 docs: [DHIS2-13299] related stages epic docs
  docs/user/resources/images/related-stages-edit-event.png
  docs/user/resources/images/related-stages-enroll-trackedEntity.png
  docs/user/resources/images/related-stages-linked-event-actions-menu.png
  docs/user/resources/images/related-stages-linked-event-view.png
  docs/user/resources/images/related-stages-maintenance.png
  docs/user/resources/images/related-stages-new-event.png
  docs/user/using-the-capture-app.md
Labels: skip-e2e-tests

#3971 fix: [DHIS2-17152] status of autogenerated events with openAfterEnrollment true
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/helpers/deriveAutoGenerateEvents.js
Labels: testing

#3975 docs: [DHIS2-13299] related stages epic developer docs
  docs/developer/enrollment-plugins/manual-setup.mdx
Labels: skip-e2e-tests

#3967 docs: add webinar
  docs/developer/develop-a-capture-plugin.md
Labels: skip-e2e-tests

#3949 feat: [DHIS2-18746][DHIS2-18903] Show org. unit in edit event form
  src/core_modules/capture-core/components/Pages/EnrollmentEditEvent/TopBar.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/TopBar.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventPage.component.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventPage.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/editEventDataEntry.actions.js
  src/core_modules/capture-core/components/WidgetEventEdit/DataEntry/epics/editEventDataEntry.epics.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/EditEventDataEntry.container.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.epics.js
  src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/ViewEventDataEntry.component.js
  src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/viewEventDataEntry.actions.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.component.js
  src/core_modules/capture-core/rules/rules.types.js
Labels: e2e-tests

#3962 fix: [DHIS2-18876] replace deprecated parameters from 2.41
  cypress/e2e/EnrollmentPage/BreakingTheGlass/BreakingTheGlass.js
  cypress/e2e/WorkingLists/TeiWorkingLists/TeiWorkingListsUser/TeiWorkingListsUser.js
  src/core_modules/capture-core-utils/featuresSupport/index.js
  src/core_modules/capture-core-utils/featuresSupport/support.js
  src/core_modules/capture-core-utils/index.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/helpers/deriveAutoGenerateEvents.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/helpers/deriveFirstStageDuringRegistrationEvent.js
  src/core_modules/capture-core/components/DataEntries/EnrollmentRegistrationEntry/hooks/useBuildEnrollmentPayload.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/getConvertedNewSingleEvent.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/saveNewSingleEvent.epics.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/saveNewSingleEventAddAnother.epics.js
  src/core_modules/capture-core/components/DataEntries/SingleEventRegistrationEntry/DataEntryWrapper/DataEntry/epics/saveNewSingleEventStage.epics.js
  src/core_modules/capture-core/components/Pages/EnrollmentAddEvent/EnrollmentAddEventPageDefault/EnrollmentAddEventPageDefault.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/ViewEvent.container.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventComponent/viewEvent.selectors.js
  src/core_modules/capture-core/components/Pages/ViewEvent/ViewEventPage.component.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/TeiSearch/epics/teiSearch.epics.js
  src/core_modules/capture-core/components/PossibleDuplicatesDialog/possibleDuplicatesDialog.epics.js
  src/core_modules/capture-core/components/SearchBox/SearchForm/SearchForm.epics.js
  src/core_modules/capture-core/components/TeiSearch/epics/teiSearch.epics.js
  src/core_modules/capture-core/components/WidgetBreakingTheGlass/WidgetBreakingTheGlass.container.js
  src/core_modules/capture-core/components/WidgetEnrollment/Actions/Transfer/hooks/useUpdateOwnership.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/getConvertedAddEvent.js
  src/core_modules/capture-core/components/WidgetEnrollmentEventNew/Validated/useBuildNewEventPayload.js
  src/core_modules/capture-core/components/WidgetEventEdit/EditEventDataEntry/editEventDataEntry.epics.js
  src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/viewEventDataEntry.actions.js
  src/core_modules/capture-core/components/WidgetEventEdit/ViewEventDataEntry/viewEventDataEntry.epics.js
  src/core_modules/capture-core/components/WidgetEventSchedule/WidgetEventSchedule.epics.js
  src/core_modules/capture-core/components/WidgetEventSchedule/hooks/useEventsInOrgUnit.js
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/FormFoundation/DataElement.js
  src/core_modules/capture-core/components/WidgetProfile/hooks/getSubValueForTei.js
  src/core_modules/capture-core/components/WidgetProfile/hooks/useClientAttributesWithSubvalues.js
  src/core_modules/capture-core/components/WidgetsRelationship/common/useRelationships/useRelationships.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/ReduxProvider/downloadRequest.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/epics/eventList.epics.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingLists/types/apiTemplate.types.js
  src/core_modules/capture-core/components/WorkingLists/EventWorkingListsCommon/EventBulkActions/Actions/CompleteAction/hooks/useBulkCompleteEvents.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/hooks/useFiltersOnly.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/Setup/hooks/useProgramStageFilters.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/TrackedEntityBulkActions/Actions/CompleteAction/hooks/useCompleteBulkEnrollments.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/TrackedEntityBulkActions/Actions/DeleteEnrollmentsAction/hooks/useDeleteEnrollments.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getEventListData/getEventListData.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/helpers/getTeiListData/getTeiListData.js
  src/core_modules/capture-core/components/WorkingLists/TeiWorkingLists/epics/teiViewEpics/retrieveTemplates.epics.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/DownloadDialog/DownloadDialog.component.js
  src/core_modules/capture-core/components/WorkingLists/WorkingListsCommon/helpers/buildFilterQueryArgs/filterConverters/assigneeConverter.js
  src/core_modules/capture-core/converters/clientToServer.js
  src/core_modules/capture-core/events/convertEventAttributeOptions.js
  src/core_modules/capture-core/events/mainConverters/mainEventClientToServerConverter.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/common/helpers/dataElement/unsupportedMultiText/handleMultiTextInUnsupportedBackendVersions.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/factory/enrollment/DataElementFactory.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/trackedEntityTypes/factory/TrackedEntityType/DataElementFactory.js
  src/core_modules/capture-core/utils/api/handleAPIResponse.js
Labels: testing

#3973 fix: [DHIS2-18714] add 'Missing search criteria' modal when adding a relationship
  i18n/en.pot
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/TeiSearch/TeiSearch.component.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/TeiSearch/TeiSearchForm/TeiSearchForm.component.js
  src/core_modules/capture-core/components/Pages/common/TEIRelationshipsWidget/TeiSearch/TeiSearchForm/TeiSearchForm.container.js
  src/core_modules/capture-core/components/TeiSearch/TeiSearch.component.js
  src/core_modules/capture-core/components/TeiSearch/TeiSearchForm/TeiSearchForm.component.js
  src/core_modules/capture-core/components/TeiSearch/TeiSearchForm/TeiSearchForm.container.js
Labels: testing

#3981 fix: [DHIS2-18855] add error logging for program indicators missing expressions
  .gitignore
  src/core_modules/capture-core/components/WidgetProfile/DataEntry/ProgramRules/rulesContainer.js
  src/core_modules/capture-core/metaDataMemoryStoreBuilders/programs/getRulesAndVariablesFromIndicators.js
Labels: testing

#3932 fix: [DHIS2-18676] display error for age in the future
  src/core_modules/capture-core/components/D2Form/field/configs/ageField/getAgeFieldConfig.js
  src/core_modules/capture-core/components/D2Form/field/defaultFormFieldGetter.js
  src/core_modules/capture-core/utils/validation/getValidators.js
  src/core_modules/capture-core/utils/validation/validators/form/ageValidator.js
  src/core_modules/capture-core/utils/validation/validators/form/index.js
  src/core_modules/capture-core/utils/validation/validators/form/isValidNonFutureAge.js
  src/core_modules/capture-ui/AgeField/ageField.module.css
Labels: testing
